---
title: "BAPTISM OF THE LORD"
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  a:
    processional:
      list:
        - name: "When Jesus Comes to Be Baptized"
          book: BB
          priority: required
    psalm:
      list:
        - name: "The Lord will bless his people with peace."
          book: RA
          priority: required
    offertory:
      list:
        - name: "Good Christian Friends, Rejoice"
          book: BB
          priority: required
    communion:
      list:
        - name: "Jesus to Jordan's Waters Came"
          book: BB
          priority: required
    meditation:
      list:
        - name: "I Have Loved You"
          book: BB
          priority: optional
        - name: "Spirit and Grace"
          book: BB
          priority: optional
    recessional:
      list:
        - name: "Go, Tell It on the Mountain"
          book: BB
          priority: required
    anthems:
      list:
        - name: "Praise to God Whose Love Was Shown"
  b:
    processional:
      list:
        - name: "When Jesus Comes to Be Baptized"
          book: BB
          priority: required
    psalm:
      list:
        - name: "You will draw water joyfully from the springs of salvation."
          book: RA
          priority: required
    offertory:
      list:
        - name: "The Snow Lay on the Ground"
          book: BB
          priority: required
    communion:
      list:
        - name: "Jesus to Jordan's Waters Came"
          book: BB
          priority: required
    meditation:
      list:
        - name: "Come to the Water"
          book: BB
          priority: required
    recessional:
      list:
        - name: "Go, Tell It on the Mountain"
          book: BB
          priority: required
  c:
    processional:
      list:
        - name: "When Jesus Comes to Be Baptized"
          book: BB
          priority: required
    psalm:
      list:
        - name: "O bless the Lord, my soul."
          book: RA
          priority: required
    offertory:
      list:
        - name: "God Rest You, Merry Gentlemen"
          book: BB
          priority: required
    communion:
      list:
        - name: "Jesus to Jordan's Waters Came"
          book: BB
          priority: required
    meditation:
      list:
        - name: "Spirit and Grace"
          book: BB
          priority: required
    recessional:
      list:
        - name: "Go, Tell It on the Mountain"
          book: BB
          priority: required
    anthems:
      list:
        - name: "Cantate Domino (Pitoni)"
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
import yaml
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)

# Video links
with open('../../_hymns.yml', 'r') as vf:
    videos = yaml.safe_load(vf)
```

:::  {.red}
#### **Themes**
:::

submission, baptism, Trinity, revelation, redemption, water

:::  {.red}
#### **Entrance Antiphon**
:::

> After the Lord was baptized, the heavens were opened,  
> and the Spirit descended upon him like a dove,  
> and the voice of the Father thundered:  
> This is my beloved Son, with whom I am well pleased.

:::  {.red}
#### **Communion Antiphon**
:::

> Behold the One of whom John said:  
> I have seen and testified that this is the Son of God.

:::: {.content-visible when-format="html"}
::: {.red}
### Readings
:::

<details>
  <summary>Click to view the readings for this liturgy.</summary>

::: {.titlered}
### &nbsp; Years A, B, C
:::

::: {.red}
#### First Reading [Isaiah 42:1-4, 6-7]{style="float:right" .small}
:::

Thus says the LORD:  
Here is my servant whom I uphold,  
&emsp; my chosen one with whom I am pleased,  
upon whom I have put my spirit;  
&emsp; he shall bring forth justice to the nations,  
not crying out, not shouting,  
&emsp; not making his voice heard in the street.  
A bruised reed he shall not break,  
&emsp; and a smoldering wick he shall not quench,  
until he establishes justice on the earth;  
&emsp; the coastlands will wait for his teaching.  

I, the LORD, have called you for the victory of justice,  
&emsp; I have grasped you by the hand;  
I formed you, and set you  
&emsp; as a covenant of the people,  
&emsp; a light for the nations,  
to open the eyes of the blind,  
&emsp; to bring out prisoners from confinement,  
&emsp; and from the dungeon, those who live in darkness.  

[Or:]{.red} [Isaiah 40:1-5, 9-11]{style="float:right" .small .red}  

Comfort, give comfort to my people,  
&emsp; says your God.  
Speak tenderly to Jerusalem, and proclaim to her  
&emsp; that her service is at an end,  
&emsp; her guilt is expiated;  
indeed, she has received from the hand of the LORD  
&emsp; double for all her sins.  

&emsp; A voice cries out:  
In the desert prepare the way of the LORD!  
&emsp; Make straight in the wasteland a highway for our God!  
Every valley shall be filled in,  
&emsp; every mountain and hill shall be made low;  
the rugged land shall be made a plain,  
&emsp; the rough country, a broad valley.   
Then the glory of the LORD shall be revealed,  
&emsp; and all people shall see it together;  
&emsp; for the mouth of the LORD has spoken.  

Go up on to a high mountain,  
&emsp; Zion, herald of glad tidings;  
cry out at the top of your voice,  
&emsp; Jerusalem, herald of good news!  
Fear not to cry out  
&emsp; and say to the cities of Judah:  
&emsp; Here is your God!  
Here comes with power  
&emsp; the Lord GOD,  
&emsp; who rules by a strong arm;  
here is his reward with him,  
&emsp; his recompense before him.  
Like a shepherd he feeds his flock;  
&emsp; in his arms he gathers the lambs,  
carrying them in his bosom,  
&emsp; and leading the ewes with care.  

***

::: {.red}
#### Responsorial Psalm [Psalm 29:1-2, 3-4, 3, 9-10]{style="float:right" .small}
:::

**[℟.]{.red}** **The Lord will bless his people with peace.**  

Give to the LORD, you sons of God,  
&emsp; give to the LORD glory and praise,  
Give to the LORD the glory due his name;  
&emsp; adore the LORD in holy attire. **[℟.]{.red}**  

The voice of the LORD is over the waters,  
&emsp; the LORD, over vast waters.  
The voice of the LORD is mighty;  
&emsp; the voice of the LORD is majestic. **[℟.]{.red}**  

The God of glory thunders,  
&emsp; and in his temple all say, “Glory!”  
The LORD is enthroned above the flood;  
&emsp; the LORD is enthroned as king forever. **[℟.]{.red}**  

[Or:]{.red} [Psalm 104:1b-2, 3-4, 24-25, 27-28, 29-30]{style="float:right" .small .red}  

**[℟.]{.red}** **O bless the Lord, my soul.**  

O LORD, my God, you are great indeed!  
&emsp; you are clothed with majesty and glory,  
robed in light as with a cloak.  
&emsp; You have spread out the heavens like a tent-cloth; **[℟.]{.red}**  

You have constructed your palace upon the waters.  
&emsp; You make the clouds your chariot;  
you travel on the wings of the wind.  
&emsp; You make the winds your messengers,  
and flaming fire your ministers. **[℟.]{.red}**  

How manifold are your works, O LORD!  
&emsp; In wisdom you have wrought them all--  
the earth is full of your creatures;  
&emsp; the sea also, great and wide,  
in which are schools without number  
&emsp; of living things both small and great. **[℟.]{.red}**  

They look to you to give them food in due time.  
&emsp; When you give it to them, they gather it;  
when you open your hand, they are filled with good things. **[℟.]{.red}**  

If you take away their breath, they perish and return to the dust.  
&emsp; When you send forth your spirit, they are created,  
and you renew the face of the earth. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [Acts 10:34-38]{style="float:right" .small}
:::

Peter proceeded to speak to those gathered  
in the house of Cornelius, saying:  
“In truth, I see that God shows no partiality.  
Rather, in every nation whoever fears him and acts uprightly  
is acceptable to him.  
You know the word that he sent to the Israelites  
as he proclaimed peace through Jesus Christ, who is Lord of all,  
what has happened all over Judea,  
beginning in Galilee after the baptism  
that John preached,  
how God anointed Jesus of Nazareth  
with the Holy Spirit and power.  
He went about doing good  
and healing all those oppressed by the devil,  
for God was with him.”  

[Or:]{.red} [Titus 2:11-14; 3:4-7]{style="float:right" .small .red}  

Beloved:  
The grace of God has appeared, saving all  
and training us to reject godless ways and worldly desires  
and to live temperately, justly, and devoutly in this age,  
as we await the blessed hope,  
the appearance of the glory of our great God  
and savior Jesus Christ,  
who gave himself for us to deliver us from all lawlessness  
and to cleanse for himself a people as his own,  
eager to do what is good.  

&emsp; When the kindness and generous love  
&emsp; &emsp; of God our savior appeared,  
&emsp; not because of any righteous deeds we had done  
&emsp; &emsp; but because of his mercy,  
&emsp; He saved us through the bath of rebirth  
&emsp; &emsp; and renewal by the Holy Spirit,  
&emsp; whom he richly poured out on us  
&emsp; &emsp; through Jesus Christ our savior,  
&emsp; so that we might be justified by his grace  
&emsp; &emsp; and become heirs in hope of eternal life.  

***

::: {.red}
#### Gospel Acclamation [Cf. Mark 9:7]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
The heavens were opened and the voice of the Father thundered:  
This is my beloved Son, listen to him. **[℟.]{.red}**  

[Or:]{.red} [Cf. Luke 3:16]{style="float:right" .small .red}  

**[℟.]{.red}** **Alleluia, alleluia.**  
John said: One mightier than I is coming;  
he will baptize you with the Holy Spirit and with fire. **[℟.]{.red}**  

***

::: {.red}
#### Gospel [Luke 3:15-16, 21-22]{style="float:right" .small}
:::

The people were filled with expectation,  
and all were asking in their hearts  
whether John might be the Christ.  
John answered them all, saying,  
“I am baptizing you with water,  
but one mightier than I is coming.  
I am not worthy to loosen the thongs of his sandals.  
He will baptize you with the Holy Spirit and fire.”  

After all the people had been baptized  
and Jesus also had been baptized and was praying,  
heaven was opened and the Holy Spirit descended upon him  
in bodily form like a dove.  
And a voice came from heaven,  
“You are my beloved Son;  
with you I am well pleased.”  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

</details>
::::

::: {.red}
## Music Selections
:::

::: {.titlered}
### &nbsp; Year A
:::
{{< var text.yeara >}}

```{python}
#| label: Year A
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['a'], urls=videos)
```

::: {.titlered}
### &nbsp; Year B
:::
{{< var text.yearb >}}

```{python}
#| label: Year B
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['b'], urls=videos)
```

::: {.titlered}
### &nbsp; Year C
:::
{{< var text.yearc >}}

```{python}
#| label: Year C
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['c'], urls=videos)
```

```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'], urls=videos)
```
