---
title: "CHRISTMAS: MASS DURING THE DAY"
subtitle: "December 25"
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  abc:
    processional:
      list:
        - name: "O Come, All Ye Faithful"
          book: BB
          priority: required
    psalm:
      list:
        - name: "All the ends of the Earth have seen the power of God."
          book: RA
          priority: optional
        - name: "Psalm 98: All the Ends of the Earth (Hurd)"
          book: BB
          priority: preferred
    offertory:
      list:
        - name: "God Rest You, Merry Gentlemen"
          year: A
          book: BB
          priority: required
        - name: "Good Christian Friends, Rejoice"
          year: B
          book: BB
          priority: required
        - name: "The Snow Lay on the Ground"
          year: C
          book: BB
          priority: required
    communion:
      list:
        - name: "It Came Upon the Midnight Clear"
          book: BB
          priority: required
    meditation:
      list:
        - name: "Of the Father’s Love Begotten"
          book: BB
          priority: required
    recessional:
      list:
        - name: "Joy to the World"
          book: BB
          priority: required
  a:
    anthems:
      list:
        - name: For Unto Us
  b:
    anthems:
      list:
        - name: Birthday of a King
  c:
    anthems:
      list:
        - name: Christ Lives Among Us
        - name: Cry Out With Joy and Gladness
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
import yaml
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)

# Video links
with open('../../_hymns.yml', 'r') as vf:
    videos = yaml.safe_load(vf)
```

:::  {.red}
#### **Themes**
:::

mystery of the Word, salvation, good news, God the Father

:::  {.red}
#### **Entrance Antiphon**
:::

> A child is born for us, and a son is given to us;  
> his scepter of power rests upon his shoulder,  
> and his name will be called Messenger of great counsel.

:::  {.red}
#### **Communion Antiphon**
:::

> All the ends of the earth have seen the salvation of our God.

:::: {.content-visible when-format="html"}
::: {.red}
### Readings
:::

<details>
  <summary>Click to view the readings for this liturgy.</summary>

::: {.red}
### &nbsp; Years A, B, C

#### First Reading [Isaiah 52:7-10]{style="float:right" .small}
:::

How beautiful upon the mountains  
&emsp; are the feet of him who brings glad tidings,  
announcing peace, bearing good news,  
&emsp; announcing salvation, and saying to Zion,  
&emsp; “Your God is King!”  

Hark!  Your sentinels raise a cry,  
&emsp; together they shout for joy,  
for they see directly, before their eyes,  
&emsp; the LORD restoring Zion.  
Break out together in song,  
&emsp; O ruins of Jerusalem!  
For the LORD comforts his people,  
&emsp; he redeems Jerusalem.  
The LORD has bared his holy arm  
&emsp; in the sight of all the nations;  
all the ends of the earth will behold  
&emsp; the salvation of our God.  

***

::: {.red}
#### Responsorial Psalm [Psalm 98:1, 2-3, 3-4, 5-6]{style="float:right" .small}
:::

**[℟.]{.red}** **All the ends of the earth have seen the saving power of God.**  

Sing to the LORD a new song,  
&emsp; for he has done wondrous deeds;  
his right hand has won victory for him,  
&emsp; his holy arm. **[℟.]{.red}**  

The LORD has made his salvation known:  
&emsp; in the sight of the nations he has revealed his justice.  
He has remembered his kindness and his faithfulness  
&emsp; toward the house of Israel. **[℟.]{.red}**  

All the ends of the earth have seen  
&emsp; the salvation by our God.  
Sing joyfully to the LORD, all you lands;  
&emsp; break into song; sing praise. **[℟.]{.red}**  

Sing praise to the LORD with the harp,  
&emsp; with the harp and melodious song.  
With trumpets and the sound of the horn  
&emsp; sing joyfully before the King, the LORD. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [Hebrews 1:1-6]{style="float:right" .small}
:::

Brothers and sisters:  
In times past, God spoke in partial and various ways  
&emsp; to our ancestors through the prophets;  
&emsp; in these last days, he has spoken to us through the Son,  
&emsp; whom he made heir of all things  
&emsp; and through whom he created the universe,  
&emsp; &emsp; who is the refulgence of his glory,  
&emsp; &emsp; &emsp; the very imprint of his being,  
&emsp; &emsp; and who sustains all things by his mighty word.  
&emsp; &emsp; When he had accomplished purification from sins,  
&emsp; &emsp; he took his seat at the right hand of the Majesty on high,  
&emsp; &emsp; as far superior to the angels  
&emsp; &emsp; as the name he has inherited is more excellent than theirs.  

For to which of the angels did God ever say:  
&emsp; *You are my son; this day I have begotten you?*  
Or again:  
&emsp; *I will be a father to him, and he shall be a son to me?*  
And again, when he leads the firstborn into the world, he says:  
&emsp; *Let all the angels of God worship him.*  

***

::: {.red}
#### Gospel Acclamation
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
A holy day has dawned upon us.  
Come, you nations, and adore the Lord.  
For today a great light has come upon the earth. **[℟.]{.red}**  

***

::: {.red}
#### Gospel [John 1:1-18 or 1:1-5, 9-14]{style="float:right" .small}
:::

&emsp; In the beginning was the Word,  
&emsp; &emsp; and the Word was with God,  
&emsp; &emsp; and the Word was God.  
&emsp; He was in the beginning with God.  
&emsp; All things came to be through him,  
&emsp; &emsp; and without him nothing came to be.  
&emsp; What came to be through him was life,  
&emsp; &emsp; and this life was the light of the human race;  
&emsp; the light shines in the darkness,  
&emsp; &emsp; and the darkness has not overcome it.  
A man named John was sent from God.  
He came for testimony, to testify to the light,  
so that all might believe through him.  
He was not the light,  
but came to testify to the light.  
The true light, which enlightens everyone, was coming into the world.  
&emsp; He was in the world,  
&emsp; &emsp; and the world came to be through him,  
&emsp; &emsp; but the world did not know him.  
&emsp; He came to what was his own,  
&emsp; &emsp; but his own people did not accept him.  

But to those who did accept him  
he gave power to become children of God,  
to those who believe in his name,  
who were born not by natural generation  
nor by human choice nor by a man’s decision  
but of God.  
&emsp; And the Word became flesh  
&emsp; &emsp; and made his dwelling among us,  
&emsp; &emsp; and we saw his glory,  
&emsp; &emsp; the glory as of the Father’s only Son,  
&emsp; &emsp; full of grace and truth.  
John testified to him and cried out, saying,  
“This was he of whom I said,  
‘The one who is coming after me ranks ahead of me  
because he existed before me.’”  
From his fullness we have all received,  
grace in place of grace,  
because while the law was given through Moses,  
grace and truth came through Jesus Christ.  
No one has ever seen God.  
The only Son, God, who is at the Father’s side,  
has revealed him.  

[Or:]{.red}  

&emsp; In the beginning was the Word,  
&emsp; &emsp; and the Word was with God,  
&emsp; &emsp; and the Word was God.  
&emsp; He was in the beginning with God.  
&emsp; All things came to be through him,  
&emsp; &emsp; and without him nothing came to be.  
&emsp; What came to be through him was life,  
&emsp; &emsp; and this life was the light of the human race;  
&emsp; the light shines in the darkness,  
&emsp; &emsp; and the darkness has not overcome it.  
The true light, which enlightens everyone, was coming into the world.  
&emsp; He was in the world,  
&emsp; &emsp; and the world came to be through him,  
&emsp; &emsp; but the world did not know him.  
&emsp; He came to what was his own,  
&emsp; &emsp; but his own people did not accept him.  

But to those who did accept him  
he gave power to become children of God,  
to those who believe in his name,  
who were born not by natural generation  
nor by human choice nor by a man’s decision  
but of God.  
&emsp; And the Word became flesh  
&emsp; &emsp; and made his dwelling among us,  
&emsp; &emsp; and we saw his glory,  
&emsp; &emsp; the glory as of the Father’s only Son,  
&emsp; &emsp; full of grace and truth.  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

</details>
::::

::: {.red}
## Music Selections
:::

::: {.titlered}
### &nbsp; Years A, B, C
:::
{{< var text.yearabc-advent >}}

```{python}
#| label: Year ABC
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['abc'], urls=videos)
```

```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'], urls=videos)
```

::: {.red}
### Notes
:::

* If available, the Festival Alleluia can be used for the Gospel Acclamation with the Christmas verse found in [Appendix B](../appendices/B-festival-alleluia.qmd).
* The Oﬀertory hymn is taken from the appropriate Liturgical Cycle.
* Additional Christmas carols can be sung at Communion as needed.