---
title: "CHRISTMAS: MASS DURING THE NIGHT (MIDNIGHT MASS)"
subtitle: "December 25"
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  abc:
    processional:
      list:
        - name: "O Come, All Ye Faithful"
          book: BB
          priority: required
    psalm:
      list:
        - name: "Today is born our Savior, Christ the Lord."
          book: RA
          priority: optional
        - name: "Psalm 96: Today is Born Our Savior"
          composer: "Hughes"
          priority: optional
        - name: "Psalm 96: Today is Born Our Savior"
          composer: "O'Brien"
          priority: optional
    offertory:
      list:
        - name: "O Little Town of Bethlehem"
          book: BB
          priority: required
    communion:
      list:
        - name: "Night of Silence / Silent Night"
          book: BB
          priority: required
    meditation:
      list:
        - name: "Of the Father’s Love Begotten"
          book: BB
          priority: optional
        - name: "O Holy Night"
          book: "[Appx A](../appendices/A-o-holy-night.qmd)"
          priority: optional
    recessional:
      list:
        - name: "Hark! The Herald Angels Sing"
          book: BB
          priority: required
  a:

    anthems:
      list:
        - name: Et in Terra Pax
        - name: For Unto Us
  b:
    anthems:
      list:
        - name: Gloria in Excelsis (Vivaldi)
        - name: Sussex Carol
  c:
    anthems:
      list:
        - name: Slumber, My Darling
        - name: Welcome the Light
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
import yaml
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)

# Video links
with open('../../_hymns.yml', 'r') as vf:
    videos = yaml.safe_load(vf)
```

:::  {.red}
#### **Themes**
:::

darkness/light, gladness, joy, glory, mystery, awe

:::  {.red}
#### **Entrance Antiphon**
:::

> The Lord said to me: You are my Son.  
> It is I who have begotten you this day.  
> 
> [Or:]{.red}
>  
> Let us all rejoice in the Lord, for our Savior has been born in the world.  
> Today true peace has come down to us from heaven.

:::  {.red}
#### **Communion Antiphon**
:::

> The Word became flesh, and we have seen his glory.

:::: {.content-visible when-format="html"}
::: {.red}
### Readings
:::

<details>
  <summary>Click to view the readings for this liturgy.</summary>

::: {.titlered}
### &nbsp; Years A, B, C
:::

::: {.red}
#### First Reading [Isaiah 9:1-6]{style="float:right" .small}
:::

The people who walked in darkness  
&emsp; have seen a great light;  
upon those who dwelt in the land of gloom  
&emsp; a light has shone.  
You have brought them abundant joy  
&emsp; and great rejoicing,  
as they rejoice before you as at the harvest,  
&emsp; as people make merry when dividing spoils.  
For the yoke that burdened them,  
&emsp; the pole on their shoulder,  
and the rod of their taskmaster  
&emsp; you have smashed, as on the day of Midian.  
For every boot that tramped in battle,  
&emsp; every cloak rolled in blood,  
&emsp; will be burned as fuel for flames.  
For a child is born to us, a son is given us;  
&emsp; upon his shoulder dominion rests.  
They name him Wonder-Counselor, God-Hero,  
&emsp; Father-Forever, Prince of Peace.  
His dominion is vast  
&emsp; and forever peaceful,  
from David’s throne, and over his kingdom,  
&emsp; which he confirms and sustains  
by judgment and justice,  
&emsp; both now and forever.  
The zeal of the LORD of hosts will do this!  

***

::: {.red}
#### Responsorial Psalm [Psalm 96: 1-2, 2-3, 11-12, 13; Luke 2:11]{style="float:right" .small}
:::

**[℟.]{.red}** **Today is born our Savior, Christ the Lord.**  

Sing to the LORD a new song;  
&emsp; sing to the LORD, all you lands.  
Sing to the LORD; bless his name. **[℟.]{.red}**  

Announce his salvation, day after day.  
&emsp; Tell his glory among the nations;  
&emsp; among all peoples, his wondrous deeds. **[℟.]{.red}**  

Let the heavens be glad and the earth rejoice;  
&emsp; let the sea and what fills it resound;  
&emsp; let the plains be joyful and all that is in them!  
Then shall all the trees of the forest exult. **[℟.]{.red}**  

They shall exult before the LORD, for he comes;  
&emsp; for he comes to rule the earth.  
He shall rule the world with justice  
&emsp; and the peoples with his constancy. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [Titus 2:11-14]{style="float:right" .small}
:::

Beloved:  
The grace of God has appeared, saving all  
and training us to reject godless ways and worldly desires  
and to live temperately, justly, and devoutly in this age,  
as we await the blessed hope,  
the appearance of the glory of our great God  
and savior Jesus Christ,  
who gave himself for us to deliver us from all lawlessness  
and to cleanse for himself a people as his own,  
eager to do what is good.  

***

::: {.red}
#### Gospel Acclamation [Luke 2:10-11]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
I proclaim to you good news of great joy:  
today a Savior is born for us,  
Christ the Lord. **[℟.]{.red}**  

***

::: {.red}
#### Gospel [Luke 2:1-14]{style="float:right" .small}
:::

In those days a decree went out from Caesar Augustus  
that the whole world should be enrolled.  
This was the first enrollment,  
when Quirinius was governor of Syria.  
So all went to be enrolled, each to his own town.  
And Joseph too went up from Galilee from the town of Nazareth  
to Judea, to the city of David that is called Bethlehem,  
because he was of the house and family of David,  
to be enrolled with Mary, his betrothed, who was with child.  
While they were there,  
the time came for her to have her child,  
and she gave birth to her firstborn son.  
She wrapped him in swaddling clothes and laid him in a manger,  
because there was no room for them in the inn.  

Now there were shepherds in that region living in the fields  
and keeping the night watch over their flock.  
The angel of the Lord appeared to them  
and the glory of the Lord shone around them,  
and they were struck with great fear.  
The angel said to them,  
“Do not be afraid;  
for behold, I proclaim to you good news of great joy  
that will be for all the people.  
For today in the city of David  
a savior has been born for you who is Christ and Lord.  
And this will be a sign for you:  
you will find an infant wrapped in swaddling clothes  
and lying in a manger.”  
And suddenly there was a multitude of the heavenly host with the angel,  
praising God and saying:  
&emsp; “Glory to God in the highest  
&emsp; &emsp; and on earth peace to those on whom his favor rests.”  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

</details>
::::

::: {.red}
## Music Selections
:::

::: {.titlered}
### &nbsp; Years A, B, C
:::
{{< var text.yearabc-advent >}}

```{python}
#| label: Year ABC
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['abc'], urls=videos)
```

```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'], urls=videos)
```

::: {.red}
### Notes
:::

* The Mass at Dawn may be celebrated at the first Mass of the morning. For simplicity, the hymns are the same as those for the [Mass During the Day](christmas-day.qmd), but the readings and Responsorial Psalm are diﬀerent. Be sure to find out which Mass the presider is celebrating and sing the correct psalm.
* If available, the Festival Alleluia can be used for the Gospel Acclamation with the Christmas Vigil verse found in [Appendix B: Festival Alleluia](../appendices/B-festival-alleluia.qmd).
* Additional Christmas carols can be sung at Communion as needed.
* "O Holy Night" can be be found in [Appendix A](../appendices/A-o-holy-night.qmd).