---
title: CHRISTMAS
---
::: {.red}
## (NATIVITY OF THE LORD)
:::

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
mass:
  abc:
    kyrie:
      list:
        - name: "Christmas Carol Mass" 
          tune: "God Rest Ye Merry Gentlemen"
          composer: "Kevin Weed"
          priority: optional
        - name: "Christmas Carol Mass"
          tune: "Angels We Have Heard on High"
          composer: "Kevin Weed"
          priority: optional
    gloria:
      list:
        - name: "Christmas Carol Mass"
          tune: "Several tunes"
          composer: "Kevin Weed"
          priority: optional
        - name: "Christmas Gloria"
          composer: "Paul Gibson"
          book: "BB"
          priority: preferred
    holy-holy-holy:
      list:
        - name: "Christmas Carol Mass"
          tune: "Once In Royal David's City"
          composer: "Kevin Weed"
          priority: required
    memorial-acclamation:
      list:
        - name: "Christmas Carol Mass"
          option: 'A ("*When we eat...*")'
          tune: "Angels We Have Heard on High"
          composer: "Kevin Weed"
          year: "A"
          priority: required
        - name: "Christmas Carol Mass"
          option: 'B ("*We proclaim...*")'
          tune: "O Little Town of Bethlehem"
          composer: "Kevin Weed"
          year: "B"
          priority: required
        - name: "Christmas Carol Mass"
          option: 'C ("*Save us...*")'
          tune: "Good Christian Men, Rejoice"
          composer: "Kevin Weed"
          year: "C"
          priority: required
    amen:
      list:
        - name: "Christmas Carol Mass"
          tune: "O Come, All Ye Faithful"
          composer: "Kevin Weed"
          priority: required
    lamb-of-god:
      list:
        - name: "Christmas Carol Mass"
          tune: "Silent Night"
          composer: "Kevin Weed"
          priority: required
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
import yaml
sys.path.append('/workspaces/planning-book')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)

# Video links
with open('../../_hymns.yml', 'r') as vf:
    videos = yaml.safe_load(vf)
```

::: {.red}
The [Christmas Carol Mass](https://kevinweed.com/christmas-carol-mass/) puts the texts of the Mass to the tunes of familiar Christmas carols, making it easy to learn and sing. It oﬀers an opportunity to increase the use of popular melodies during the short Christmas season. The Mass setting includes options for the [Memorial Acclamation]{.black} and the [Great Amen]{.black}; the preferred version for each is provided here:
:::

::: {.titlered}
### &nbsp; Year A, B, C
:::
{{< var text.yearabc >}}

```{python}
#| title: Year ABC
#| echo: false
#| output: asis
utils.masssetting(params['mass']['abc'], urls=videos)
```

::: {.red}
(This setting is not currently available through any of the three major publishers. It will need to be purchased for public liturgical use [here](https://kevinweed.com/christmas-carol-mass/).)

Alternatively, the Mass parts during the season of Christmas can be taken from the appropriate [Liturgical Cycle](../ordinary-time/ot.qmd), using the [Christmas Gloria]{.black} instead of the Gloria from the Mass setting.
:::

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::