---
title: "EPIPHANY OF THE LORD"
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  abc:
    processional:
      list:
        - name: "Songs of Thankfulness and Praise"
          book: BB
          priority: required
    psalm:
      list:
        - name: "Lord, every nation on earth will adore you."
          book: RA
          priority: required
    offertory:
      list:
        - name: "We Three Kings"
          book: BB
          priority: required
    communion:
      list:
        - name: "The First Nowell"
          book: BB
          priority: preferred
        - name: "What Child is This"
          book: BB
          priority: optional
    meditation:
      list:
        - name: "What Star Is This"
          book: BB
          priority: required
    recessional:
      list:
        - name: "As With Gladness Men of Old"
          book: BB
          priority: required
  a:
    anthems:
      list:
        - name: Welcome the Light
  b:
    anthems:
      list:
        - name: Wood of the Cradle
  c:
    anthems:
      list:
        - name: "Nowell! Nowell! Nowell!"
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
import yaml
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)

# Video links
with open('../../_hymns.yml', 'r') as vf:
    videos = yaml.safe_load(vf)
```

:::  {.red}
#### **Themes**
:::

universality, revelation, glory, wisdom

:::  {.red}
#### **Entrance Antiphon**
:::

> Behold, the Lord, the Mighty One, has come;  
> and kingship is in his grasp, and power and dominion.

:::  {.red}
#### **Communion Antiphon**
:::

> We have seen his star in the East,  
> and have come with gifts to adore the Lord.

:::: {.content-visible when-format="html"}
::: {.red}
### Readings
:::

<details>
  <summary>Click to view the readings for this liturgy.</summary>

::: {.titlered}
### &nbsp; Years A, B, C
:::

::: {.red}
#### First Reading [Isaiah 60:1-6]{style="float:right" .small}
:::

Rise up in splendor, Jerusalem! Your light has come,  
the glory of the Lord shines upon you.  
See, darkness covers the earth,  
and thick clouds cover the peoples;  
but upon you the LORD shines,  
and over you appears his glory.  
Nations shall walk by your light,  
and kings by your shining radiance.  
Raise your eyes and look about;  
they all gather and come to you:  
your sons come from afar,  
and your daughters in the arms of their nurses.  

Then you shall be radiant at what you see,  
your heart shall throb and overflow,  
for the riches of the sea shall be emptied out before you,  
the wealth of nations shall be brought to you.  
Caravans of camels shall fill you,  
dromedaries from Midian and Ephah;  
all from Sheba shall come  
bearing gold and frankincense,  
and proclaiming the praises of the LORD.  

***

::: {.red}
#### Responsorial Psalm [Psalm 72:1-2, 7-8, 10-11, 12-13]{style="float:right" .small}
:::

**[℟.]{.red}** **Lord, every nation on earth will adore you.**  

O God, with your judgment endow the king,  
and with your justice, the king’s son;  
He shall govern your people with justice  
and your afflicted ones with judgment. **[℟.]{.red}**  

Justice shall flower in his days,  
and profound peace, till the moon be no more.  
May he rule from sea to sea,  
and from the River to the ends of the earth. **[℟.]{.red}**  

The kings of Tarshish and the Isles shall offer gifts;  
the kings of Arabia and Seba shall bring tribute.  
All kings shall pay him homage,  
all nations shall serve him. **[℟.]{.red}**  

For he shall rescue the poor when he cries out,  
and the afflicted when he has no one to help him.  
He shall have pity for the lowly and the poor;  
the lives of the poor he shall save. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [Ephesians 3:2-3a, 5-6]{style="float:right" .small}
:::

Brothers and sisters:  
You have heard of the stewardship of God’s grace  
that was given to me for your benefit,  
namely, that the mystery was made known to me by revelation.  
It was not made known to people in other generations  
as it has now been revealed  
to his holy apostles and prophets by the Spirit:  
that the Gentiles are coheirs, members of the same body,  
and copartners in the promise in Christ Jesus through the gospel.  

***

::: {.red}
#### Gospel Acclamation [Matthew 2:2]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
We saw his star at its rising  
and have come to do him homage. **[℟.]{.red}**  

***

::: {.red}
#### Gospel [Matthew 2:1-12]{style="float:right" .small}
:::

When Jesus was born in Bethlehem of Judea,  
in the days of King Herod,  
behold, magi from the east arrived in Jerusalem, saying,  
“Where is the newborn king of the Jews?  
We saw his star at its rising  
and have come to do him homage.”  
When King Herod heard this,  
he was greatly troubled,  
and all Jerusalem with him.  
Assembling all the chief priests and the scribes of the people,  
he inquired of them where the Christ was to be born.  
They said to him, “In Bethlehem of Judea,  
for thus it has been written through the prophet:  
*And you, Bethlehem, land of Judah,*  
*are by no means least among the rulers of Judah;*  
*since from you shall come a ruler,*  
*who is to shepherd my people Israel.*”  
Then Herod called the magi secretly  
and ascertained from them the time of the star’s appearance.  
He sent them to Bethlehem and said,  
“Go and search diligently for the child.  
When you have found him, bring me word,  
that I too may go and do him homage.”  
After their audience with the king they set out.  
And behold, the star that they had seen at its rising preceded them,  
until it came and stopped over the place where the child was.  
They were overjoyed at seeing the star,  
and on entering the house  
they saw the child with Mary his mother.  
They prostrated themselves and did him homage.  
Then they opened their treasures  
and offered him gifts of gold, frankincense, and myrrh.  
And having been warned in a dream not to return to Herod,   
they departed for their country by another way.  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

</details>
::::

::: {.red}
## Music Selections
:::

::: {.titlered}
### &nbsp; Years A, B, C
:::
{{< var text.yearabc >}}

```{python}
#| label: Year ABC
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['abc'], urls=videos)
```

```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'], urls=videos)
```
