---
title: "HOLY FAMILY OF JESUS, MARY, AND JOSEPH"
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  a:
    processional:
      list:
        - name: "Angels, from the Realms of Glory"
          book: BB
          priority: required
    psalm:
      list:
        - name: "Blessed are those who fear the Lord and walk in his ways."
          book: RA
          priority: required
    offertory:
      list:
        - name: "While Shepherds Watched Their Flock"
          book: BB
          priority: required
    communion:
      list:
        - name: "Once in Royal David’s City"
          book: BB
          priority: required
    meditation:
      list:
        - name: "Infant Holy, Infant Lowly"
          book: BB
          priority: required
    recessional:
      list:
        - name: "Angels We Have Heard on High"
          book: BB
          priority: required
    anthems:
      list:
        - name: "And Love Was Born (Sewell)"
        - name: "Sing Lullaby"
  b:
    processional:
      list:
        - name: "Angels, from the Realms of Glory"
          book: BB
          priority: required
    psalm:
      list:
        - name: "The Lord remembers his covenant for ever."
          book: RA
          priority: required
    offertory:
      list:
        - name: "Infant Holy, Infant Lowly"
          book: BB
          priority: required
    communion:
      list:
        - name: "Once in Royal David’s City"
          book: BB
          priority: required
    meditation:
      list:
        - name: "Luke 2: Song of Simeon"
          book: BB
          priority: required
    recessional:
      list:
        - name: "Hark! The Herald Angels Sing"
          book: BB
          priority: preferred
    anthems:
      list:
        - name: "Thou Must Leave Thy Lowly Dwelling"
  c:
    processional:
      list:
        - name: "Angels, from the Realms of Glory"
          book: BB
          priority: required
    psalm:
      list:
        - name: "Blessed are they who dwell in your house, O Lord."
          book: RA
          priority: required
    offertory:
      list:
        - name: "O Come, Little Children"
          book: BB
          priority: required
    communion:
      list:
        - name: "Once in Royal David’s City"
          book: BB
          priority: required
    meditation:
      list:
        - name: "Infant Holy, Infant Lowly"
          book: BB
          priority: required
    recessional:
      list:
        - name: "Joy to the World"
          book: BB
          priority: required
    anthems:
      list:
        - name: "Cold Was the Stable"
        - name: "O How Amiable"
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
import yaml
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)

# Video links
with open('../../_hymns.yml', 'r') as vf:
    videos = yaml.safe_load(vf)
```

:::  {.red}
#### **Themes**
:::

family life, love, understanding, spiritual growth

:::  {.red}
#### **Entrance Antiphon**
:::

> The shepherds went in haste,  
> and found Mary and Joseph and the Infant lying in a manger.

:::  {.red}
#### **Communion Antiphon**
:::

> Our God has appeared on the earth, and lived among us.

:::: {.content-visible when-format="html"}
::: {.red}
### Readings
:::

<details>
  <summary>Click to view the readings for this liturgy.</summary>

::: {.red}
### &nbsp; Years A, B, C

#### First Reading [Sirach 3:2-6, 12-14]{style="float:right" .small}
:::

God sets a father in honor over his children;  
a mother’s authority he confirms over her sons.  
Whoever honors his father atones for sins,  
and preserves himself from them.  
When he prays, he is heard;  
he stores up riches who reveres his mother.  
Whoever honors his father is gladdened by children,  
and, when he prays, is heard.  
Whoever reveres his father will live a long life;  
he who obeys his father brings comfort to his mother.  

My son, take care of your father when he is old;  
grieve him not as long as he lives.  
Even if his mind fail, be considerate of him;  
revile him not all the days of his life;  
kindness to a father will not be forgotten,  
firmly planted against the debt of your sins  
—a house raised in justice to you.  

[Or:]{.red} [Genesis 15:1-6; 21:1-3]{style="float:right" .small .red}  

The word of the LORD came to Abram in a vision, saying:  
“Fear not, Abram!  
I am your shield;  
I will make your reward very great.”  
But Abram said,  
“O Lord GOD, what good will your gifts be,  
if I keep on being childless  
and have as my heir the steward of my house, Eliezer?”  
Abram continued,  
“See, you have given me no offspring,  
and so one of my servants will be my heir.”  
Then the word of the LORD came to him:  
“No, that one shall not be your heir;  
your own issue shall be your heir.”  
The Lord took Abram outside and said,  
“Look up at the sky and count the stars, if you can.  
Just so,” he added, “shall your descendants be.”  
Abram put his faith in the LORD,  
who credited it to him as an act of righteousness.  

The LORD took note of Sarah as he had said he would;  
he did for her as he had promised.  
Sarah became pregnant and bore Abraham a son in his old age,  
at the set time that God had stated.  
Abraham gave the name Isaac to this son of his  
whom Sarah bore him.  

***

::: {.red}
#### Responsorial Psalm [Psalm 128:1-2, 3, 4-5]{style="float:right" .small}
:::

**[℟.]{.red}** **Blessed are those who fear the Lord and walk in his ways.**  

Blessed is everyone who fears the LORD,  
who walks in his ways!  
For you shall eat the fruit of your handiwork;  
blessed shall you be, and favored. **[℟.]{.red}**  

Your wife shall be like a fruitful vine  
in the recesses of your home;  
your children like olive plants  
around your table. **[℟.]{.red}**  

Behold, thus is the man blessed  
who fears the LORD.  
The LORD bless you from Zion:  
may you see the prosperity of Jerusalem  
all the days of your life. **[℟.]{.red}**  

[Or:]{.red} [Psalm 105:1-2, 3-4, 5-6, 8-9]{style="float:right" .small .red}  

**[℟.]{.red}** **The Lord remembers his covenant for ever.**  

Give thanks to the LORD, invoke his name;  
make known among the nations his deeds.  
Sing to him, sing his praise,  
proclaim all his wondrous deeds. **[℟.]{.red}**  

Glory in his holy name;  
rejoice, O hearts that seek the LORD!  
Look to the LORD in his strength;  
constantly seek his face. **[℟.]{.red}**  

You descendants of Abraham, his servants,  
sons of Jacob, his chosen ones!  
He, the LORD, is our God;  
throughout the earth his judgments prevail. **[℟.]{.red}**  

He remembers forever his covenant  
which he made binding for a thousand generations  
which he entered into with Abraham  
and by his oath to Isaac. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [Colossians 3:12-21 or 3:12-17]{style="float:right" .small}
:::

Brothers and sisters:  
Put on, as God’s chosen ones, holy and beloved,  
heartfelt compassion, kindness, humility, gentleness, and patience,  
bearing with one another and forgiving one another,  
if one has a grievance against another;  
as the Lord has forgiven you, so must you also do.  
And over all these put on love,  
that is, the bond of perfection.  
And let the peace of Christ control your hearts,  
the peace into which you were also called in one body.  
And be thankful.  
Let the word of Christ dwell in you richly,  
as in all wisdom you teach and admonish one another,  
singing psalms, hymns, and spiritual songs  
with gratitude in your hearts to God.  
And whatever you do, in word or in deed,  
do everything in the name of the Lord Jesus,  
giving thanks to God the Father through him.  

Wives, be subordinate to your husbands,  
as is proper in the Lord.  
Husbands, love your wives,  
and avoid any bitterness toward them.  
Children, obey your parents in everything,  
for this is pleasing to the Lord.  
Fathers, do not provoke your children,  
so they may not become discouraged.  

[Or:]{.red}  

Brothers and sisters:  
Put on, as God’s chosen ones, holy and beloved,  
heartfelt compassion, kindness, humility, gentleness, and patience,  
bearing with one another and forgiving one another,  
if one has a grievance against another;  
as the Lord has forgiven you, so must you also do.  
And over all these put on love,  
that is, the bond of perfection.  
And let the peace of Christ control your hearts,  
the peace into which you were also called in one body.  
And be thankful.  
Let the word of Christ dwell in you richly,  
as in all wisdom you teach and admonish one another,  
singing psalms, hymns, and spiritual songs  
with gratitude in your hearts to God.  
And whatever you do, in word or in deed,   
do everything in the name of the Lord Jesus,  
giving thanks to God the Father through him.  

[Or:]{.red} [Hebrews 11:8, 11-12, 17-19]{style="float:right" .small .red}  

Brothers and sisters:  
By faith Abraham obeyed when he was called to go out to a place  
that he was to receive as an inheritance;  
he went out, not knowing where he was to go.  
By faith he received power to generate,  
even though he was past the normal age  
--and Sarah herself was sterile--  
for he thought that the one who had made the promise was trustworthy.  
So it was that there came forth from one man,  
himself as good as dead,  
descendants as numerous as the stars in the sky  
and as countless as the sands on the seashore.  

By faith Abraham, when put to the test, offered up Isaac,  
and he who had received the promises was ready to offer  
his only son,  
of whom it was said,  
“Through Isaac descendants shall bear your name.”  
He reasoned that God was able to raise even from the dead,  
and he received Isaac back as a symbol.  

***

::: {.red}
#### Gospel Acclamation [Colossians 3:15a, 16a]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
Let the peace of Christ control your hearts;  
let the word of Christ dwell in you richly. **[℟.]{.red}**  

[Or:]{.red} [Hebrews 1:1-2 ]{style="float:right" .small .red}

**[℟.]{.red}** **Alleluia, alleluia.**  
In the past God spoke to our ancestors through the prophets;  
in these last days, he has spoken to us through the Son. **[℟.]{.red}**  

***

::: {.red}
#### Gospel [Luke 2:22-40 or 2:22, 39-40]{style="float:right" .small}
:::

When the days were completed for their purification  
according to the law of Moses,  
They took him up to Jerusalem  
to present him to the Lord,  
just as it is written in the law of the Lord,  
Every male that opens the womb shall be consecrated to the Lord,  
and to offer the sacrifice of  
a pair of turtledoves or two young pigeons,  
in accordance with the dictate in the law of the Lord.  

Now there was a man in Jerusalem whose name was Simeon.  
This man was righteous and devout,  
awaiting the consolation of Israel,  
and the Holy Spirit was upon him.  
It had been revealed to him by the Holy Spirit  
that he should not see death  
before he had seen the Christ of the Lord.  
He came in the Spirit into the temple;  
and when the parents brought in the child Jesus  
to perform the custom of the law in regard to him,  
He took him into his arms and blessed God, saying:  
“Now, Master, you may let your servant go  
in peace, according to your word,  
for my eyes have seen your salvation,  
which you prepared in sight of all the peoples,  
a light for revelation to the Gentiles,  
and glory for your people Israel.”  
The child’s father and mother were amazed at what was said about him;  
and Simeon blessed them and said to Mary his mother,  
“Behold, this child is destined  
for the fall and rise of many in Israel,  
and to be a sign that will be contradicted  
—and you yourself a sword will pierce—  
so that the thoughts of many hearts may be revealed.”  
There was also a prophetess, Anna,  
the daughter of Phanuel, of the tribe of Asher.  
She was advanced in years,  
having lived seven years with her husband after her marriage,  
and then as a widow until she was eighty-four.  
She never left the temple,  
but worshiped night and day with fasting and prayer.  
And coming forward at that very time,  
she gave thanks to God and spoke about the child  
to all who were awaiting the redemption of Jerusalem.  

When they had fulfilled all the prescriptions  
of the law of the Lord,  
they returned to Galilee,  
to their own town of Nazareth.  
The child grew and became strong, filled with wisdom;  
and the favor of God was upon him.  

[Or:]{.red}  

When the days were completed for their purification  
according to the law of Moses,  
they took him up to Jerusalem  
to present him to the Lord.  

When they had fulfilled all the prescriptions  
of the law of the Lord,  
they returned to Galilee,  
to their own town of Nazareth.  
The child grew and became strong, filled with wisdom;  
and the favor of God was upon him.  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

</details>
::::

::: {.red}
## Music Selections
:::

::: {.titlered}
### &nbsp; Year A
:::
{{< var text.yeara-advent >}}

```{python}
#| label: Year A
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['a'], urls=videos)
```

::: {.titlered}
### &nbsp; Year B
:::
{{< var text.yearb-advent >}}

```{python}
#| label: Year B
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['b'], urls=videos)
```

::: {.titlered}
### &nbsp; Year C
:::
{{< var text.yearc-advent >}}

```{python}
#| label: Year C
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['c'], urls=videos)
```

```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'], urls=videos)
```

::: {.red}
### Notes
:::

* When a Sunday does not occur between December 25 and January 1, this feast is celebrated as a weekday Mass on December 30 with only one reading before the Gospel.
