# About the Author {#sec-author}

Matthew Grossi has been serving in Catholic music ministries for more than two decades. With humble beginnings as an occasional substitute organist at Sacred Heart, St. Peter, and St. Francis parishes in Torrington, Connecticut (now St. John Paul the Great Parish), he started playing regularly at liturgies as a pianist for the Catholic Campus Ministry at Florida Institute of Technology in Melbourne, Florida. He later served as a weekly organist at St. Jude the Apostle Church in Lewes, Delaware before returning to New England where he become principal organist at Our Lady of Lourdes Church in Carver, Massachusetts and St. Lawrence, Martyr Church in New Bedford, Massachusetts, while simultaneously substituting at numerous churches throughout Rhode Island and southeastern Massachusetts including St. Anthony of Padua, Mattapoisett; St. Rita of Cascia, Marion; St. Margaret, Buzzards Bay; St. Mary, Onset; and St. Patrick, Wareham. He most recently served as organist and music planner at St. Kieran Catholic Church in Miami, Florida, where he oversaw the purchase and installation of a new state-of-the-art Rodgers Infinity 351 digital organ.

Matt studied philosophy at Providence College in Providence, Rhode Island and theology and liturgy at St. John’s Seminary in Brighton, Massachusetts. Music ministry is just his hobby: he is an oceanographer and studies the motion of the ocean full-time. He holds Bachelor of Science, Master of Science, and Doctor of Philosophy degrees, all in physical oceanography, and works as a civil servant for the National Oceanic and Atmospheric Administration (NOAA).