<!-- "`{=html}
<style>
.center {
   text-align: center;
}
</style>
"` -->


# Introduction

[*"The musical tradition of the universal Church is a treasure of inestimable value, greater even than that of any other art. The main reason for this pre-eminence is that, as sacred song united to the words, it forms a necessary or integral part of the solemn liturgy."*]{.red}

::: {.flushright}
{{< var symbols.cross >}} [*Sacrosanctum concilium*, 112]{.red}
:::

::: {.center .italic}
When, in our music, God is glorified,  
And adoration leaves no room for pride,  
It is as though the whole creation cried:  
Alleluia!

So has the Church, in liturgy and song,  
In faith and love, through centuries of wrong,  
Borne witness to the truth in ev'ry tongue:  
Alleluia!  
:::


The text of Fred Pratt Green's well-known hymn "When in Our Music God is Glorified" beautifully captures the high esteem in which sacred music is held within the Catholic Church, and why.
Though Pratt Green was not Catholic himself (the hymn was originally written for the Presbyterian church in England in 1972 [@hawn2013]), the theology captured by the Methodist poet's prose harmonizes closely with that of several important Catholic documents. 
This reality speaks to the universality, centrality, and shared understanding of music within the larger Christian church around the world, even while other theological debates prevail.
In his encyclical [*Mediator Dei*](https://www.vatican.va/content/pius-xii/en/encyclicals/documents/hf_p-xii_enc_20111947_mediator-dei.html) (*MD*; "On the Sacred Liturgy"), @md proclaims regarding sacred music:

> It is not merely a question of recitation or of singing which, however perfect according to norms of music and the sacred rites, only reaches the ear, but it is especially a question of the ascent of the mind and heart to God so that, united with Christ, we may completely dedicate ourselves and all our actions to Him (*MD*, 145).

Indeed, this is the sole purpose of music in the liturgy: that it may inspire all of creation to worship and glorify God, in profound adoration, and ascend to Him in mind and heart to be united in the truth of Christ's sacrifice on the altar.
Alleluia!

Praying through song is a very Jewish practice wherein the Catholic liturgy finds its roots.
Scholarly consensus is that the Book of Psalms, also called the Psalter, is a collection of songs routinely used in Jewish worship, though how they were sung has been lost to history in the absence of musical notation in antiquity.
("Psalter" comes from the Greek "*Psalterion*," the string-instrument used for the accompaniment of songs or psalms.)
For Jesus, as a Jew, to pray the psalms was to *sing* the psalms, as he does numerous times throughout the Gospels.
The psalter contains songs of glory and praise, supplication and thanksgiving, suffering and lamentation.
They capture every emotion, occasion, and aspect of the human experience, from the most joyful to the most agonizing.
Thusly does Pratt Green's hymn go on:

::: {.italic}
And did not Jesus sing a psalm that night  
When utmost evil strove against the light?  
Then let us sing, for whom he won the fight:  
Alleluia!
:::

When the Church sings psalms during Mass, the Liturgy of the Hours, or at just about every other liturgical celebration to this day, she does so in fidelity to how those same ancient songs were prayed by Jesus himself.

The Catholic Church has always held sacred music in high esteem and, especially since the Second Vatican Council, has advocated for the participation of the faithful in music at Mass and other liturgical celebrations.
Truth be told, however, one could compellingly argue that Protestant denominations have perfected what the Catholic Church professes in the musical arena.
It is hardly uncommon in many mainstream Protestant churches---including the most liturgical denominations whose worship traditions remain similar to those of the Catholic Church---to find everyone with an open hymnal singing wholeheartedly to the best of their ability with the voice God gave them, through every verse of every song without complaint, even breaking out into four part harmony.
Compare that to the average Catholic congregation, especially in Western English-speaking cultures!
Yet the Catholic Church, in the Second Vatican Council's ["Constitution on the Sacred Liturgy," *Sacrosanctum concilium*](https://www.vatican.va/archive/hist_councils/ii_vatican_council/documents/vat-ii_const_19631204_sacrosanctum-concilium_en.html) (*SD*), calls for just that: "[W]henever the sacred action is to be celebrated with song, the *whole body of the faithful* may be able to contribute that *active participation* which is rightly theirs" ([@sd, 114, emphasis added]).


The Church recognizes and has acknowledged this unfortunate disconnect between profession and practice.
Pope Pius XII did not mince words when he wrote,

> Indeed it is very necessary that the faithful attend the sacred ceremonies not as if they were outsiders or mute onlookers, but let them fully appreciate the beauty of the liturgy and take part in the sacred ceremonies, alternating their voices with the priest and the choir, according to the prescribed norms (*MD*, 192).

Although he was addressing the Mass as a whole, the statement certainly includes music, for:

> [a] congregation that is devoutly present at the sacrifice, in which our Savior together with His children redeemed with His sacred blood sings the nuptial hymn of His immense love, cannot keep silent, for "song befits the lover" and, as the ancient saying has it, "he who sings well prays twice."

And if that was not sufficiently clear, Pius also exhorted music ministers "to promote with care congregational singing, and to see to its accurate execution with all due dignity, since it easily stirs up and arouses the faith and piety of large gatherings of the faithful" (*MD*, 192).
Fifteen years later, Pope Paul VI reaffirmed this directive in *SC* (118): 

> Religious singing by the people is to be intelligently fostered so that in devotions and sacred exercises, as also during liturgical services, the voices of the faithful may ring out according to the norms and requirements of the rubrics.

Clearly, the active singing participation of the people in the pews is important!

To be fair, Catholic parishes that have truly taken these teachings to heart do exist---and how wonderful and refreshing it is to find one!
Nevertheless, in the majority of English-speaking parishes, much work remains to be done, both in terms of the quality of music provided and the active participation in the music.
Herein lies the commendable responsibility of music ministers, instrumentalists, song leaders (cantors), and choir members alike.
The humble Catholic music minister will admit that much can be learned from our Protestant brethren.
Differences in theology and practices do still exist, however, and Catholic Tradition must be understood and respected, and "the treasure of sacred music...preserved and fostered with great care" (*SC*, 114).

This "treasure of sacred music" is vast and rich, and giving it due justice is well beyond the scope of the present reflection.
Within this trove are everything from Gregorian chant to polyphony, from four-part choir anthems to more recent songs by contemporary composers.
Despite recent debates on the appropriateness of contemporary music in Catholic liturgy, *MD* (193) confirms that 

> [i]t cannot be said that modern music and singing should be entirely excluded from Catholic worship. For, if they are not profane nor unbecoming to the sacredness of the place and function, and do not spring from a desire of achieving extraordinary and unusual effects, then our churches must admit them since they can contribute in no small way to the splendor of the sacred ceremonies, can lift the mind to higher things and foster true devotion of soul.


Because different types of music inspire different people, parish repertoires should ideally include some of everything, where and when appropriate, and as long as it deemed suitable for Catholic worship.
Discernment and informed scrutiny are necessary: not every song that mentions God is sacred.
*SC* (121) explains that "texts intended to be sung must always be in conformity with Catholic doctrine; indeed they should be drawn chiefly from holy scripture and from liturgical sources."
(This is why so-called "pop culture" songs are never appropriate within Catholic liturgy.)
Indeed, the Church encourages composers 

> filled with the Christian spirit...[to] produce compositions which have the qualities proper to genuine sacred music, not confining themselves to works which can be sung only by large choirs, but providing also for the needs of small choirs and for the active participation of the entire assembly of the faithful (*SC*, 121).


Diligent attention must also be given to *how* liturgical music is performed.
Cantors must be comfortable leading congregational singing, as this is precisely their role.
"Choirs must be diligently promoted" (*SC*, 114) when and where appropriate.
People are more inclined to join in singing if they hear others singing around them; thus, strong, well-trained choirs have the potential to be just as effective, if not more so, than cantors at encouraging congregational singing.
The choice of instrument must also be carefully considered.
The Roman Catholic (*i.e.*, Latin) Church holds the pipe organ in "high esteem, for it is the traditional musical instrument which adds a wonderful splendor to the Church's ceremonies and powerfully lifts up man's mind to God and to higher things" (*SC*, 120).
While other instruments are permitted, it must be ensured that they "are suitable, or can be made suitable, for sacred use, accord with the dignity of the temple, and truly contribute to the edification of the faithful" (*SC*, 120).
For example, an acoustic guitar may be sufficient for a small group gathering, but wholly inadequate for filling a large church with sound.
The instrument is not only to lead the cantor; it must lead and inspire the entire congregation.

*Sacrosanctum concilium* devotes an entire chapter to liturgical music, which opens with the quote preceding this Introduction:

> The musical tradition of the universal Church is a treasure of inestimable value, greater even than that of any other art. The main reason for this pre-eminence is that, as sacred song united to the words, it forms a necessary or integral part of the solemn liturgy. Therefore sacred music is to be considered the more holy in proportion as it is more closely connected with the liturgical action, whether it adds delight to prayer, fosters unity of minds, or confers greater solemnity upon the sacred rites (*SC*, 112).

This bold statement is worthy of contemplation.
"The musical tradition of the universal Church is...*greater even than that of any other art*."
Imagine stepping into Saint Peter's Basilica in Rome---or any other famously ornate cathedral in the world---for the first time and being awestruck by the beauty of the architecture, the frescos, the stained glass windows, the sanctuary.
Many a tourist who profess no religious belief or practice admit a certain indescribable "other-worldliness" of the stunning and breathtaking beauty found inside the walls of historic Catholic churches---which is precisely the intended response.
The Church claims that as strong a response invoked by these most beautiful works of art, liturgical music should be even more impactful.
The stakes are undoubtedly high!

The music minister's role is therefore crucially important.
Music must be performed well so as to enhance the liturgy and elevate the minds and hearts of the worshipers.
This must not be mistaken for theatrical performance for entertainment; at its core, liturgical music must be worship.
The music minister must lead the congregation in such a way as to invite, encourage, and inspire full, conscious, and active participation, that all might

> [join] in the hymns of the Church triumphant and with the choirs of angels, and, all together, sing a wondrous and eternal hymn of praise to the most Holy Trinity in keeping with words of the preface, "with whom our voices, too, thou wouldst bid to be admitted" (*MD*, 192).

And equally important, the music minister must ensure that the music is suitable for worship and appropriately selected for the specific celebration.
Only in this way can the music fully harmonize with the readings and spoken prayers of the liturgy to create one holistic act of worship worthy of Almighty God.

Thus, to the devoted and dedicated music minister: Go forth, produce beautiful music worthy of our God and inspiring to worshipers, that through your hard work, long hours of planning, practice, and rehearsals behind the scenes, and commitment to enhancing liturgical worship, the Catholic faithful entrusted to your musical care may truly ascend to God in mind and heart, week after week, in full, active, conscious participation.
May the beauty of the music you provide surpass that of the most stunningly ornate church.
And may the final verse of Fred Pratt Green's hymn "When In Our Music God is Glorified" ring true in every church every weekend:

::: {.italic}
Let every instrument be tuned for praise!  
Let all rejoice who have a voice to raise!  
And may God give us faith to sing always:  
Alleluia!
:::

In the words of Pope Pius XII:

> Let the full harmonious singing of our people rise to heaven like the bursting of a thunderous sea and let them testify by the melody of their song to the unity of their hearts and minds, as becomes brothers and the children of the same Father (*MD*, 194).

And in the words of the psalmist:

::: {.italic}
Praise God with the sounding of the trumpet,  
\hspace*{10pt} praise him with the harp and lyre,  
Praise him with timbrel and dancing,  
\hspace*{10pt} praise him with the strings and pipe,  
Praise him with the clash of cymbals,  
\hspace*{10pt} praise him with resounding cymbals.  
\hspace*{12em} (Psalm 150 3-5)
:::

*Saint Cecilia, patroness of music and musicians, pray for us!*

::: {.center}
{{< var symbols.crosses >}}
:::