---
title: NTH Sunday of SEASON
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  a:
    processional:
      list:
        - name: 
          tune: 
          verses: 
          composer: 
          book: BB
          priority: required
    psalm:
      list:
        - name: 
          book: RA
          priority: required
    offertory:
      list:
        - name: 
          book: BB
          priority: required
    communion:
      list:
        - name: 
          book: BB
          priority: required
    meditation:
      list:
        - name: 
          book: BB
          composer: 
          priority: required
    recessional:
      list:
        - name: 
          book: BB
          priority: required
  b:
    processional:
      list:
        - name: 
          book: BB
          priority: required
    psalm:
      list:
        - name: 
          book: RA
          priority: required
    offertory:
      list:
        - name: 
          book: BB
          priority: required
    communion:
      list:
        - name: 
          book: BB
          priority: required
    meditation:
      list:
        - name: 
          book: BB
          priority: required
    recessional:
      list:
        - name: 
          book: BB
          priority: preferred
    anthems:
      list:
        - name: 
  c:
    processional:
      list:
        - name: 
          book: BB
          priority: required
    psalm:
      list:
        - name: 
          book: RA
          priority: required
    offertory:
      list:
        - name: 
          book: BB
          priority: required
    communion:
      list:
        - name: 
          book: BB
          composer: 
          tune: 
          verses: 
          priority: required
    meditation:
      list:
        - name: 
          book: BB
          priority: required
    recessional:
      list:
        - name: 
          book: BB
          priority: required
    anthems:
      list:
        - name: 
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
import yaml
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)

# Video links
with open('../../_hymns.yml', 'r') as vf:
    videos = yaml.safe_load(vf)
```

:::  {.red}
#### **Themes**
:::

THEMES

:::  {.red}
#### **Entrance Antiphon**
:::

> ENTRANCE ANTIPHON  

:::  {.red}
#### **Communion Antiphon**
:::

> COMMUNION ANTIPHON

:::: {.content-visible when-format="html"}
::: {.red}
### Readings
:::

<details>
  <summary>Click to view the readings for this liturgy.</summary>

::: {.red}
### &nbsp; Year A

#### First Reading [PASSAGE]{style="float:right" .small}
:::

Text  
&ensp; indented as needed

***

::: {.red}
#### Responsorial Psalm [PASSAGE]{style="float:right" .small}
:::

**[℟.]{.red}** **REFRAIN.**  

Verse one,
&emsp; indented as needed. **[℟.]{.red}**  

Verse two,  
&emsp; and so on as needed. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [PASSAGE]{style="float:right" .small}
:::

Text

***

::: {.red}
#### Alleluia [PASSAGE]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
Verse **[℟.]{.red}**

***

::: {.red}
#### Gospel [PASSAGE]{style="float:right" .small}
:::

Text

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

::: {.red}
### &nbsp; Year B

#### First Reading [PASSAGE]{style="float:right" .small}
:::

Text

***

::: {.red}
#### Responsorial Psalm [PASSAGE]{style="float:right" .small}
:::

**[℟.]{.red}** **REFRAIN**  

Verse one,  
&emsp; indented as needed. **[℟.]{.red}**  

Verse two,
&emsp; and so on as needed. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [PASSAGE]{style="float:right" .small}
:::

Text

***

::: {.red}
#### Alleluia [PASSAGE]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
Verse **[℟.]{.red}**  

***

::: {.red}
#### Gospel [PASSAGE]{style="float:right" .small}
:::

Text

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

::: {.red}
### &nbsp; Year C

#### First Reading [PASSAGE]{style="float:right" .small}
:::

Text  
&ensp; indented as needed.

***

::: {.red}
#### Responsorial Psalm [PASSAGE]{style="float:right" .small}
:::

**[℟.]{.red}** **REFRAIN**  

Verse one,  
&emsp; indented as needed. **[℟.]{.red}**  

Verse two,
&emsp; and so on as needed. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [PASSAGE]{style="float:right" .small}
:::

Text

***

::: {.red}
#### Alleluia [PASSAGE]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
Verse. **[℟.]{.red}** 

***

::: {.red}
#### Gospel [PASSAGE]{style="float:right" .small}
:::

Text

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

</details>
::::

::: {.red}
## Music Selections
:::

::: {.titlered}
### &nbsp; Year A
:::
{{< var text.yeara >}}

```{python}
#| label: Year A
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['a'], urls=videos)
```

::: {.titlered}
### &nbsp; Year B
:::
{{< var text.yearb >}}

```{python}
#| label: Year B
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['b'], urls=videos)
```

::: {.titlered}
### &nbsp; Year C
:::
{{< var text.yearc >}}

```{python}
#| label: Year C
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['c'], urls=videos)
```


```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'], urls=videos)
```

::: {.red}
### Notes
:::

* NOTES