---
title: "THE PASCHAL PROCLAMATION (*EXSULTET*)"
subtitle: Easter Vigil
---

::: {.red}
The Paschal Proclamation, also known as the *Exsculet*, is an ancient proclamation that consecrates the Paschal (Easter) Candle during the [Easter Vigil](../holy-week/easter-vigil.qmd) celebration.

The cantor may be asked by the Presider to chant this, if the Presider is uncomfortable chanting it himself. In this situation, the cantor should be extremely comfortable with this important – and lengthy – chant, which is to be done a capella and in the dark. Be sure to confirm with the Presider whether to chant the long version (provided here, usually preferred) or the optional shorter version. Regardless of the version used, the cantor must always omit the section for Deacon/Priest only; see instructions that accompany the Proclamation.

<a href="./exultet-revised.pdf" target="_blank">Click to download</a> the Paschal (Easter) Proclamation.
:::

<!-- ```{=html}
<object data="exultet-revised.pdf#toolbar=0&navpanes=0&scrollbar=0" type="application/pdf" width="100%" height="100%">
    <p>It appears you don't have a PDF plugin for this browser.
    No biggie... you can <a href="exultet-revised.pdf">click here to download the PDF file.</a></p>
</object>
``` -->

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::
