---
title: "FIRST SUNDAY OF ADVENT"
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  a:
    processional:
      list:
        - name: "Come, Thou Long-Expected Jesus"
          tune: stuttgart
          book: "Breaking Bread"
          priority: required
    psalm:
      list:
        - name: "Let us go rejoicing to the house of the Lord."
          book: "Respond and Acclaim"
          priority: required
    offertory:
      list:
        - name: "The Advent of Our King"
          book: "Breaking Bread"
          priority: preferred
        - name: "Lord of All Hopefulness"
          book: "Breaking Bread"
          priority: optional
    communion:
      list:
        - name: "Wake, O Wake, and Sleep No Longer"
          book: "Breaking Bread"
          priority: required
    meditation:
      list:
        - name: "Maranatha"
          composer: Westphal
          book: "Breaking Bread"
          priority: required
    recessional:
      list:
        - name: "City of God"
          book: "Breaking Bread"
          priority: required
  b:
    processional:
      list:
        - name: "Come Now, Almighty King"
          book: "Breaking Bread"
          priority: required
    psalm:
      list:
        - name: "Lord, make us turn to you; let us see your face and we shall be saved."
          book: "Respond and Acclaim"
          priority: required
    offertory:
      list:
        - name: "The Advent of Our King"
          book: "Breaking Bread"
          priority: required
    communion:
      list:
        - name: "Eye Has Not Seen"
          book: "Breaking Bread"
          priority: required
    meditation:
      list:
        - name: "Abba! Father"
          book: "Breaking Bread"
          priority: required
    recessional:
      list:
        - name: "O Come, Divine Messiah"
          book: "Breaking Bread"
          priority: preferred
    anthems:
      list:
        - name: "When Will He Come?"
  c:
    processional:
      list:
        - name: "The King of Glory"
          book: "Breaking Bread"
          priority: required
    psalm:
      list:
        - name: "To You, O Lord, I lift my soul."
          book: "Breaking Bread"
          priority: required
    offertory:
      list:
        - name: "The Advent of Our King"
          book: "Breaking Bread"
          priority: preferred
        - name: "Lord of All Hopefulness"
          book: "Breaking Bread"
          priority: optional
    communion:
      list:
        - name: "Bread of Life"
          composer: Farrell
          tune: "Advent/Christmas"
          book: "Breaking Bread"
          verses: 1-2
          priority: optional
        - name: "Savior of the Nations, Come"
          book: "Breaking Bread"
          priority: optional
    meditation:
      list:
        - name: "Beyond the Moon and Stars"
          book: "Breaking Bread"
          priority: required
    recessional:
      list:
        - name: "Lift Up Your Heads, Ye Mighty Gates"
          book: "Breaking Bread"
          priority: preferred
        - name: "In the Day of the Lord"
          book: "Breaking Bread"
          priority: optional
    anthems:
      list:
        - name: "Lo! He Comes With Clouds Descending"
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
import yaml
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)

# Video links
with open('../../_hymns.yml', 'r') as vf:
    videos = yaml.safe_load(vf)
```

:::  {.red}
#### **Themes**
:::

waiting, trust, charity, hope, promise, light/dark, Second Coming, vigilance, urgency

:::  {.red}
#### **Entrance Antiphon**
:::

> To you, I lift up my soul, O my God.  
> In you, I have trusted; let me not be put to shame.  
> Nor let my enemies exult over me; and let none who hope in you be put to
shame.

:::  {.red}
#### **Communion Antiphon**
:::

> The Lord will bestow his bounty, and our earth shall yield its increase.

:::: {.content-visible when-format="html"}
::: {.red}
### Readings
:::

<details>
  <summary>Click to view the readings for this liturgy.</summary>

::: {.titlered}
### &nbsp; Year A
:::

::: {.red}
#### First Reading [Isaiah 2:1-5]{style="float:right" .small}
:::

This is what Isaiah, son of Amoz,  
saw concerning Judah and Jerusalem.  
In days to come,  
the mountain of the LORD's house  
shall be established as the highest mountain  
and raised above the hills.  
All nations shall stream toward it;  
many peoples shall come and say:  
"Come, let us climb the LORD's mountain,  
to the house of the God of Jacob,  
that he may instruct us in his ways,  
and we may walk in his paths."  
For from Zion shall go forth instruction,  
and the word of the LORD from Jerusalem.  
He shall judge between the nations,  
and impose terms on many peoples.  
They shall beat their swords into plowshares  
and their spears into pruning hooks;  
one nation shall not raise the sword against another,  
nor shall they train for war again.  
O house of Jacob, come,  
let us walk in the light of the Lord!  

***

::: {.red}
#### Responsorial Psalm [Psalm 122: 1-2, 3-4, 4-5, 6-7, 8-9]{style="float:right" .small}
:::

**[℟.]{.red}** **Let us go rejoicing to the house of the Lord.**  

I rejoiced because they said to me,  
"We will go up to the house of the LORD."  
And now we have set foot  
within your gates, O Jerusalem. **[℟.]{.red}**  

Jerusalem, built as a city  
with compact unity.  
To it the tribes go up,  
the tribes of the LORD. **[℟.]{.red}**  

According to the decree for Israel,  
to give thanks to the name of the LORD.  
In it are set up judgment seats,  
seats for the house of David. **[℟.]{.red}**  

Pray for the peace of Jerusalem!  
May those who love you prosper!  
May peace be within your walls,  
prosperity in your buildings. **[℟.]{.red}**  

Because of my brothers and friends  
I will say, "Peace be within you!"  
Because of the house of the LORD, our God,  
I will pray for your good. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [Romans 13:11-14]{style="float:right" .small}
:::

Brothers and sisters:  
You know the time;  
it is the hour now for you to awake from sleep.  
For our salvation is nearer now than when we first believed;  
the night is advanced, the day is at hand.  
Let us then throw off the works of darkness  
and put on the armor of light;  
let us conduct ourselves properly as in the day,  
not in orgies and drunkenness,  
not in promiscuity and lust,  
not in rivalry and jealousy.  
But put on the Lord Jesus Christ,  
and make no provision for the desires of the flesh.  

***

::: {.red}
#### Gospel Acclamation [Cf. Psalm 85:8]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
Show us Lord, your love;  
and grant us your salvation. **[℟.]{.red}**  

***

::: {.red}
#### Gospel [Matthew 24:37-44]{style="float:right" .small}
:::

Jesus said to his disciples:  
"As it was in the days of Noah,  
so it will be at the coming of the Son of Man.  
In those days before the flood,  
they were eating and drinking,  
marrying and giving in marriage,  
up to the day that Noah entered the ark.  
They did not know until the flood came and carried them all away.  
So will it be also at the coming of the Son of Man.  
Two men will be out in the field;  
one will be taken, and one will be left.  
Two women will be grinding at the mill;  
one will be taken, and one will be left.  
Therefore, stay awake!  
For you do not know on which day your Lord will come.  
Be sure of this: if the master of the house  
had known the hour of night when the thief was coming,  
he would have stayed awake  
and not let his house be broken into.  
So too, you also must be prepared,  
for at an hour you do not expect, the Son of Man will come."  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

::: {.titlered}
### &nbsp; Year B
:::

::: {.red}
#### First Reading [Isaiah 63:16b-17, 19b; 64:2-7]{style="float:right" .small}
:::

You, LORD, are our father,  
our redeemer you are named forever.  
Why do you let us wander, O LORD, from your ways,  
and harden our hearts so that we fear you not?  
Return for the sake of your servants,  
the tribes of your heritage.  
Oh, that you would rend the heavens and come down,  
with the mountains quaking before you,  
while you wrought awesome deeds we could not hope for,  
such as they had not heard of from of old.  
No ear has ever heard, no eye ever seen, any God but you  
doing such deeds for those who wait for him.  
Would that you might meet us doing right,  
that we were mindful of you in our ways!  
Behold, you are angry, and we are sinful;  
all of us have become like unclean people,  
all our good deeds are like polluted rags;  
we have all withered like leaves,  
and our guilt carries us away like the wind.  
There is none who calls upon your name,  
who rouses himself to cling to you;  
for you have hidden your face from us  
and have delivered us up to our guilt.  
Yet, O LORD, you are our father;  
we are the clay and you the potter:  
we are all the work of your hands.  

***

::: {.red}
#### Responsorial Psalm [Psalm 80:2-3, 15-16, 18-19]{style="float:right" .small}
:::

**[℟.]{.red}** **Lord, make us turn to you; let us see your face and we shall be saved.**  

O shepherd of Israel, hearken,  
from your throne upon the cherubim, shine forth.  
Rouse your power,  
and come to save us. **[℟.]{.red}**  

Once again, O LORD of hosts,  
look down from heaven, and see;  
take care of this vine,  
and protect what your right hand has planted  
the son of man whom you yourself made strong. **[℟.]{.red}**  

May your help be with the man of your right hand,  
with the son of man whom you yourself made strong.  
Then we will no more withdraw from you;  
give us new life, and we will call upon your name. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [1 Corinthians 1:3-9]{style="float:right" .small}
:::

Brothers and sisters:  
Grace to you and peace from God our Father  
and the Lord Jesus Christ.  

I give thanks to my God always on your account  
for the grace of God bestowed on you in Christ Jesus,  
that in him you were enriched in every way,  
with all discourse and all knowledge,  
as the testimony to Christ was confirmed among you,  
so that you are not lacking in any spiritual gift  
as you wait for the revelation of our Lord Jesus Christ.  
He will keep you firm to the end,  
irreproachable on the day of our Lord Jesus Christ.  
God is faithful,  
and by him you were called to fellowship with his Son,  
Jesus Christ our Lord.  

***

::: {.red}
#### Gospel Acclamation [Psalm 85:8]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
Show us Lord, your love;  
and grant us your salvation. **[℟.]{.red}**  

***

::: {.red}
#### Gospel [Mark 13:33-37]{style="float:right" .small}
:::

Jesus said to his disciples:  
“Be watchful! Be alert!  
You do not know when the time will come.  
It is like a man traveling abroad.  
He leaves home and places his servants in charge,  
each with his own work,  
and orders the gatekeeper to be on the watch.  
Watch, therefore;  
you do not know when the lord of the house is coming,  
whether in the evening, or at midnight,  
or at cockcrow, or in the morning.  
May he not come suddenly and find you sleeping.  
What I say to you, I say to all: ‘Watch!’”  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

::: {.titlered}
### &nbsp; Year C
:::

::: {.red}
#### First Reading [Jeremiah 33:14-16]{style="float:right" .small}
:::

The days are coming, says the LORD,  
&emsp; when I will fulfill the promise  
&emsp; I made to the house of Israel and Judah.  
In those days, in that time,  
&emsp; I will raise up for David a just shoot;  
&emsp; he shall do what is right and just in the land.  
In those days Judah shall be safe  
&emsp; and Jerusalem shall dwell secure;  
&emsp; this is what they shall call her:  
&emsp; “The LORD our justice.”  

***

::: {.red}
#### Responsorial Psalm [Psalm 25:4-5, 8-9, 10, 14]{style="float:right" .small}
:::

**[℟.]{.red}** **To you, O Lord, I lift my soul.**  

Your ways, O LORD, make known to me;  
&emsp; teach me your paths,  
Guide me in your truth and teach me,  
&emsp; for you are God my savior,  
&emsp; and for you I wait all the day. **[℟.]{.red}**  

Good and upright is the LORD;  
&emsp; thus he shows sinners the way.  
He guides the humble to justice,  
&emsp; and teaches the humble his way. **[℟.]{.red}**  

All the paths of the LORD are kindness and constancy  
&emsp; toward those who keep his covenant and his decrees.  
The friendship of the LORD is with those who fear him,  
&emsp; and his covenant, for their instruction. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [1 Thessalonians 3:12—4:2]{style="float:right" .small}
:::

Brothers and sisters:  
May the Lord make you increase and abound in love  
for one another and for all,  
just as we have for you,  
so as to strengthen your hearts,  
to be blameless in holiness before our God and Father  
at the coming of our Lord Jesus with all his holy ones. Amen.  

Finally, brothers and sisters,  
we earnestly ask and exhort you in the Lord Jesus that,  
as you received from us  
how you should conduct yourselves to please God  
and as you are conducting yourselves  
you do so even more.  
For you know what instructions we gave you through the Lord Jesus.  

***

::: {.red}
#### Gospel Acclamation [Psalm 85:8]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
Show us, Lord, your love;  
and grant us your salvation. **[℟.]{.red}**  

***

::: {.red}
#### Gospel [Luke 21:25-28, 34-36]{style="float:right" .small}
:::

Jesus said to his disciples:  
“There will be signs in the sun, the moon, and the stars,  
and on earth nations will be in dismay,  
perplexed by the roaring of the sea and the waves.  
People will die of fright  
in anticipation of what is coming upon the world,  
for the powers of the heavens will be shaken.  
And then they will see the Son of Man  
coming in a cloud with power and great glory.  
But when these signs begin to happen,  
stand erect and raise your heads  
because your redemption is at hand.  

“Beware that your hearts do not become drowsy  
from carousing and drunkenness  
and the anxieties of daily life,   
and that day catch you by surprise like a trap.  
For that day will assault everyone  
who lives on the face of the earth.  
Be vigilant at all times  
and pray that you have the strength  
to escape the tribulations that are imminent  
and to stand before the Son of Man.”  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

</details>
::::

::: {.red}
## Music Selections
:::

::: {.titlered}
### &nbsp; Year A
:::
{{< var text.yeara-advent >}}

```{python}
#| label: Year A
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['a'], urls=videos)
```

::: {.titlered}
### &nbsp; Year B
:::
{{< var text.yearb-advent >}}

```{python}
#| label: Year B
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['b'], urls=videos)
```

::: {.titlered}
### &nbsp; Year C
:::
{{< var text.yearc-advent >}}

```{python}
#| label: Year C
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['c'], urls=videos)
```


```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'], urls=videos, index='anthems')
```

::: {.red}
### Notes
:::

* The **Gloria** is omitted during Advent.