---
title: "Solemnity of the Most Holy Body and Blood of Christ (*Corpus Christi*)"
subtitle: Second Sunday after Pentecost
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  a:
    processional:
      list:
        - name: "Praise to the Lord"
          book: BB
          priority: required
    psalm:
      list:
        - name: "Praise the Lord, Jerusalem."
          book: RA
          priority: required
    sequence:
      list:
        - name: "Sequence for *Corpus Christi*"
          book: Appendix H
          priority: required
    offertory:
      list:
        - name: "One Love Released"
          book: BB
          priority: preferred
        - name: "One Bread, One Body"
          book: BB
          priority: optional
    communion:
      list:
        - name: "Seed, Scattered and Sown"
          book: BB
          priority: preferred
        - name: "Shepherd of Souls"
          book: BB
          priority: optional
    meditation:
      list:
        - name: "O Sacrament Most Holy"
          book: BB
          priority: preferred
        - name: "Let All Mortal Flesh Keep Silence"
          book: BB
          priority: optional
    recessional:
      list:
        - name: "Holy God, We Praise Thy Name"
          book: BB
          priority: required
    anthems:
      list:
        - name: "Lauda, Jerusalem"
  b:
    processional:
      list:
        - name: "At the Lamb's High Feast"
          book: BB
          priority: required
    psalm:
      list:
        - name: "I will take the cup of salvation, and call on the name of the Lord."
          book: RA
          priority: required
    sequence:
      list:
        - name: "Sequence for *Corpus Christi*"
          book: Appendix H
          priority: required
    offertory:
      list:
        - name: "O Sacrament Most Holy"
          book: BB
          priority: preferred
        - name: "Alleluia! Sing to Jesus"
          book: BB
          priority: optional
    communion:
      list:
        - name: "Take and Eat"
          book: BB
          priority: required
    meditation:
      list:
        - name: "Panis Angelicus"
          tune: "sacris solemniis"
          book: BB
          priority: required
    recessional:
      list:
        - name: "Holy God, We Praise Thy Name"
          book: BB
          priority: required
    anthems:
      list:
        - name: "Panis Angelicus"
          composer: Franck
  c:
    processional:
      list:
        - name: "Alleluia! Sing to Jesus"
          book: BB
          priority: required
    psalm:
      list:
        - name: "You are a priest for ever, in the line of Melchizedek."
          book: RA
          priority: required
    sequence:
      list:
        - name: "Sequence for *Corpus Christi*"
          book: Appendix H
          priority: required
    offertory:
      list:
        - name: "Gift of Finest Wheat"
          book: BB
          priority: required
    communion:
      list:
        - name: "O Sacrament Most Holy"
          book: BB
          priority: required
    meditation:
      list:
        - name: "Jesus, My Lord, My God, My All"
          book: BB
          priority: required
    recessional:
      list:
        - name: "Holy God, We Praise Thy Name"
          book: BB
          priority: required
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
import yaml
sys.path.append('/workspaces/planning-book')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)

# Video links
with open('../../_hymns.yml', 'r') as vf:
    videos = yaml.safe_load(vf)
```

:::  {.red}
#### **Themes**
:::

Eucharist, love

:::  {.red}
#### **Entrance Antiphon**
:::

> He fed them with the finest wheat  
> and satisfied them with honey from the rock.

:::  {.red}
#### **Communion Antiphon**
:::

> Whoever eats my flesh and drinks my blood  
> remains in me and I in him, says the Lord.

::: {.titlered}
### &nbsp; Year A
:::
{{< var text.yeara >}}

```{python}
#| title: Year A
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['a'], urls=videos)
```

::: {.titlered}
### &nbsp; Year B
:::
{{< var text.yearb >}}

```{python}
#| title: Year B
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['b'], urls=videos)
```

::: {.titlered}
### &nbsp; Year C
:::
{{< var text.yearc >}}

```{python}
#| title: Year C
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['c'], urls=videos)
```


```{python}
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'], urls=videos)
```

::: {.red}
### Notes
:::

* The optional **Sequence**, found in Appendix H, is sung by the cantor
only immediately after the Second Reading. Either the long or short
version may be used at the discretion of the presider. Musicians must
coordinate with the presider before Mass to determine if the Sequence is
desired, and if so, whether the long or short version is preferred.
Accompaniment should be soft and reverent, like Meditation hymns.
* If a Eucharist Procession takes place after Mass, “Lauda, Jerusalem”, as
found in Appendix I: Lauda, Jerusalem, can be sung, cycling through
verses 1-4 as many times as needed and concluding with either verse 5 or
6 upon reaching the final destination, as in the recording.
* If Adoration of the Blessed Sacrament takes place during or after Mass,
the music is taken from Appendix J.