---
title: Solemnity of Saint Joseph, Spouse of Mary
subtitle: March 19
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  abc:
    processional:
      list:
        - name: "By All Your Saints Still Striving"
          verses: "1, 4*, and 3"
          book: BB
          priority: required
    psalm:
      list:
        - name: "The son of David will live forever."
          book: "[Appx C](../appendices/C-mar19-psalm.qmd)"
          priority: required
    offertory:
      list:
        - name: "Be Not Afraid"
          book: BB
          priority: preferred
    communion:
      list:
        - name: "Holy Patron, Thee Saluting"
          book: BB
          priority: required
    meditation:
      list:
        - name: "Dwelling Place"
          book: BB
          priority: preferred
    recessional:
      list:
        - name: "Faith of Our Fathers"
          book: BB
          priority: required
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
import yaml
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)

# Video links
with open('../../_hymns.yml', 'r') as vf:
    videos = yaml.safe_load(vf)
```

:::  {.red}
#### **Themes**
:::

fidelity, righteousness, stewardship

:::  {.red}
#### **Entrance Antiphon**
:::

> Behold, a faithful and prudent steward,  
> whom the Lord set over his household.

:::  {.red}
#### **Communion Antiphon**
:::

> Well done, good and faithful servant.  
> Come, share you master's joy.

::: {.titlered}
### &nbsp; Years A, B, C
:::
{{< var text.yearabc >}}

```{python}
#| label: Years ABC
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['abc'], urls=videos)
```


```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'], urls=videos)
```

::: {.red}
### Notes
:::

* *The first (generic) verse should be sung followed by the special verse for this feast.
* The **Responsorial Psalm** is found in [Appendix C](../appendices/C-mar19-psalm.qmd).
* If this Solemnity falls within the season of Lent, the **Lenten Gospel Acclamation** in [Appendix C](../appendices/C-mar19-psalm.qmd) is sung.
* If this Solemnity *does not* fall within the season of Lent, the verse text in [Appendix C](../appendices/C-mar19-psalm.qmd) is sung with a familiar “Alleluia” refrain. In this case, if the verse accompaniment from [Appendix C](../appendices/C-mar19-psalm.qmd) is also used, either the chosen refrain should be in the same key as the verse (F major or D minor), or the verse should be transposed to the key signature of the chosen refrain.