---
title: Solemnity of the Annunciation of the Lord
subtitle: March 25
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  abc:
    processional:
      list:
        - name: "By All Your Saints Still Striving"
          verses: "1, 5*, and 3"
          book: BB
          priority: preferred
        - name: "Sing of Mary"
          book: BB
          priority: optional
    psalm:
      list:
        - name: "Here I am, Lord; I come to do your will."
          book: RA
          priority: preferred
        - name: "Psalm 40: Here I Am"
          composer: Cooney
          book: BB
          priority: optional
    offertory:
      list:
        - name: "Here I Am, Lord" 
          book: BB
          priority: required
    communion:
      list:
        - name: "Hail Mary, Gentle Woman"
          book: BB
          priority: required
    meditation:
      list:
        - name: "The Angel Gabriel from Heaven Came"
          book: BB
          priority: required
    recessional:
      list:
        - name: "Hail, Holy Queen"
          book: BB
          priority: required
    anthems:
      list:
        - name: "Dixit Maria"
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
import yaml
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)

# Video links
with open('../../_hymns.yml', 'r') as vf:
    videos = yaml.safe_load(vf)
```

:::  {.red}
#### **Themes**
:::

faith, fidelity, Mary, trust

:::  {.red}
#### **Entrance Antiphon**
:::

> The Lord said, as he entered the world:  
> Behold, I come to do your will, O God.

:::  {.red}
#### **Communion Antiphon**
:::

> Behold, a Virgin shall conceive and bear a son;  
> and his name will be called Emmanuel.

::: {.titlered}
### &nbsp; Year ABC
:::
{{< var text.yearabc >}}

```{python}
#| label: Years ABC
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['abc'], urls=videos)
```


```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'], urls=videos)
```

::: {.red}
### Notes
:::

* *The first (generic) verse should be sung followed by the special verse for this solemnity.
* The **Gloria** is sung or recited. If sung, all Mass parts are taken from the Mass setting for the given year as specified in the [Ordinary Time
preamble](../ordinary-time/ordinary-time.qmd).
* If this solemnity falls within the season of Lent, the **Lenten Gospel
Acclamation** found in Appendix D is sung.
* If this Solemnity *does not* fall within the season of Lent, the verse text in Appendix D is sung with a familiar “Alleluia” refrain. In this case, if the verse accompaniment from Appendix D is also used, either the chosen refrain should be in the same key as the verse (F major or D minor), or the verse should be transposed to the key signature of the chosen refrain.