---
title: Good Friday of the Lord's Passion
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  a:
    psalm:
      list:
        - name: "Father, into your hands I commend my spirit."
          book: RA
          priority: preferred
        - name: "Psalm 31: Father, I Put My Life In Your Hands"
          composer: Talbot
          book: BB
          priority: optional
    veneration-of-the-cross:
      list:
        - name: "When I Survey the Wondrous Cross"
          book: BB
          priority: required
    communion:
      list:
        - name: "O Sacred Head, Surrounded"
          tune: "PASSION CHORALE"
          book: BB
          priority: required
    meditation:
      list:
        - name: "Jesus, Remember Me"
          book: BB
          note: "*a capella*"
          priority: required
    anthems:
      list:
        - name: "God So Loved the World"
          composer: "John Stainer"
  b:
    psalm:
      list:
        - name: "Father, into your hands I commend my spirit."
          book: RA
          priority: preferred
        - name: "Psalm 31: Father, I Put My Life In Your Hands"
          composer: Talbot
          book: BB
          priority: optional
    veneration-of-the-cross:
      list:
        - name: "Sing, My Tongue, the Savior’s Glory"
          tune: "PANGE LINGUA GLORIOSI"
          book: BB
          priority: optional
        - name: "Were You There"
          book: BB
          priority: optional
    communion:
      list:
        - name: "What Wondrous Love"
          book: BB
          priority: required
    meditation:
      list:
        - name: "Jesus, Remember Me"
          book: BB
          note: "*a capella*"
          priority: required
    anthems:
      list:
        - name: "Near the Cross"
          composer: "William H. Doane"
        - name: "When Jesus Wept"
          composer: "William Billings"
  c:
    psalm:
      list:
        - name: "Father, into your hands I commend my spirit."
          book: RA
          priority: preferred
        - name: "Psalm 31: Father, I Put My Life In Your Hands"
          composer: Talbot
          book: BB
          priority: optional
    offertory:
      list:
        - name: "At the Cross Her Station Keeping"
          book: BB
          priority: required
    communion:
      list:
        - name: "Who Is the Crucified?"
          book: BB
          priority: required
    meditation:
      list:
        - name: "Jesus, Remember Me"
          book: BB
          note: "*a capella*"
          priority: required
    anthems:
      list:
        - name: "Lord, Let Me Walk"
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
import yaml
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)

# Video links
with open('../../_hymns.yml', 'r') as vf:
    videos = yaml.safe_load(vf)
```

:::  {.red}
#### **Themes**
:::

silence, awe, cross, passion & death, salvation, triumph

:::  {.red}
#### **Entrance Antiphon**
:::

*No Entrance Antiphon*

:::  {.red}
#### **Communion Antiphon**
:::

*No Communion Antiphon*

::: {.titlered}
### &nbsp; Year A
:::
{{< var text.yeara >}}

```{python}
#| title: Year A
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['a'], urls=videos)
```

::: {.titlered}
### &nbsp; Year B
:::
{{< var text.yearb >}}

```{python}
#| title: Year B
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['b'], urls=videos)
```

::: {.titlered}
### &nbsp; Year C
:::
{{< var text.yearc >}}

```{python}
#| title: Year C
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['c'], urls=videos)
```


```{python}
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'], urls=videos)
```

::: {.red}
### Notes
:::

* The Holy Triduum–--Holy Thursday, Good Friday, and the Easter Vigil---
is one single liturgy. Thus, there is no processional or recessional hymn
on Good Friday. All gather and depart in **silence**.
* No prelude or postlude music is permitted. The organ and other musical
instruments may be used only so as to support singing.
* No music rehearsals of any kind, including singer warm-ups, should take
place in the church before this service. Sacred silence is to be diligently
respected by all.
* If given the option, the hymn “Were You There” should be taken from GIA,
either the Gather or Worship hymnal, which usually have more verses than Breaking Bread.
* Choral anthems oﬀered as alternatives or in addition to hymns listed for
the Veneration of the Cross, Communion hymn, or Meditation hymn. Good Friday should be coordinated with Palm Sunday to avoid repeating anthems.