---
title: PALM SUNDAY OF THE LORD'S PASSION
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  a:
    processional:
      list:
        - name: "All Glory, Laud, and Honor"
          book: BB
          priority: required
    psalm:
      list:
        - name: "My God, my God, why have you abandoned me?"
          book: RA
          priority: preferred
        - name: "Psalm 22: My God, My God"
          composer: Manion
          book: BB
          priority: optional
    offertory:
      list:
        - name: "At the Name of Jesus"
          tune: "KING'S WESTON"
          book: BB
          priority: required
    communion:
      list:
        - name: "What Wondrous Love"
          book: BB
          priority: required
    meditation:
      list:
        - name: "Jesus, Remember Me"
          book: BB
          note:  "*a capella*"
          priority: required
    recessional:
      list:
        - name: "Lift High the Cross"
          book: BB
          priority: required
    anthems:
      list:
        - name: "Near the Cross"
          composer: "William H. Doane"
        - name: "Lord, Let Me Walk"
  b:
    processional:
      list:
        - name: "All Glory, Laud, and Honor"
          book: BB
          priority: required
    psalm:
      list:
        - name: "My God, my God, why have you abandoned me?"
          book: RA
          priority: preferred
        - name: "Psalm 22: My God, My God"
          composer: Manion
          book: BB
          priority: optional
    offertory:
      list:
        - name: "Crown Him With Many Crowns"
          book: BB
          priority: required
    communion:
      list:
        - name: "O Sacred Head, Surrounded"
          tune: "PASSION CHORALE"
          book: BB
          priority: required
    meditation:
      list:
        - name: "Hail, Redeemer, King Divine"
          book: BB
          priority: required
    recessional:
      list:
        - name: "Lift High the Cross"
          book: BB
          priority: required
    anthems:
      list:
        - name: "God So Loved the World"
          composer: "John Stainer"
        - name: "Jesus Walked This Lonesome Valley"
  c:
    processional:
      list:
        - name: "All Glory, Laud, and Honor"
          book: BB
          priority: required
    psalm:
      list:
        - name: "My God, my God, why have you abandoned me?"
          book: RA
          priority: preferred
        - name: "Psalm 22: My God, My God"
          composer: Manion
          book: BB
          priority: optional
    offertory:
      list:
        - name: "At the Name of Jesus"
          composer: "Walker"
          book: BB
          priority: required
    communion:
      list:
        - name: "Were You There"
          book: BB
          priority: required
    meditation:
      list:
        - name: "Jesus, Remember Me"
          book: BB
          note:  "*a capella*"
          priority: required
    recessional:
      list:
        - name: "Lift High the Cross"
          book: BB
          priority: required
    anthems:
      list:
        - name: "When Jesus Wept"
          composer: "William Billings"
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
import yaml
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)

# Video links
with open('../../_hymns.yml', 'r') as vf:
    videos = yaml.safe_load(vf)
```

:::  {.red}
#### **Themes**
:::

triumph/passion, glory/suﬀering

:::  {.red}
#### **Entrance Antiphon**
:::

> Hosanna to the Son of David;  
> blessed is he who comes in the name of the Lord,  
> the King of Israel. Hosanna in the highest.

:::  {.red}
#### **Communion Antiphon**
:::

> Father, if this chalice cannot pass without my drinking it,  
> your will be done.

::: {.titlered}
### &nbsp; Year A
:::
{{< var text.yeara >}}

```{python}
#| title: Year A
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['a'], urls=videos)
```

::: {.titlered}
### &nbsp; Year B
:::
{{< var text.yearb >}}

```{python}
#| title: Year B
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['b'], urls=videos)
```

::: {.titlered}
### &nbsp; Year C
:::
{{< var text.yearc >}}

```{python}
#| title: Year C
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['c'], urls=videos)
```


```{python}
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'], urls=videos)
```

::: {.red}
### Notes
:::

* The **Gloria** is omitted during Lent.
* The Palm Sunday liturgy begins at the rear of the church. The
**Processional Hymn** is not sung until after the first Gospel reading and
the priest concludes with “*...let us go forth in peace.*”
* If given the option, the hymn “Were You There” should be taken from GIA,
either the Gather or Worship hymnal, which usually have more
verses than Breaking Bread.
* Choral anthems oﬀered are alternatives for the **Meditation hymn**.
Palm Sunday should be coordinated with Good Friday to avoid repeating
anthems.