---
title: Third Sunday of Easter
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  a:
    processional:
      list:
        - name: "Alleluia No. 1"
          book: BB
          priority: preferred
    psalm:
      list:
        - name: "Lord, you will show us the path of life."
          book: RA
          priority: required
    offertory:
      list:
        - name: "Two Were Bound for Emmaus"
          book: BB
          priority: required
    communion:
      list:
        - name: "In the Breaking of the Bread"
          composer:  Hurd
          book: BB
          priority: required
    meditation:
      list:
        - name: "I Know that My Redeemer Lives"
          composer: Soper
          book: BB
          priority: required
    recessional:
      list:
        - name: "Alleluia! Alleluia! Let the Holy Anthem Rise"
          book: BB
          priority: required
    anthems:
      list:
        - name: "Thine Be the Glory"
  b:
    processional:
      list:
        - name: "All Creatures of Our God and King"
          book: BB
          priority: preferred
    psalm:
      list:
        - name: "Lord, let your face shine on us."
          book: RA
          priority: required
    offertory:
      list:
        - name: "Now the Green Blade Rises"
          book: BB
          priority: preferred
    communion:
      list:
        - name: "In the Breaking of the Bread"
          composer:  Hurd
          book: BB
          priority: required
    meditation:
      list:
        - name: "Peace"
          book: BB
          priority: required
    recessional:
      list:
        - name: "Three Days"
          tune: THAXTED
          note: "all verses"
          book: BB
          priority: required
  c:
    processional:
      list:
        - name: "At the Lamb's High Feast"
          book: BB
          priority: required
    psalm:
      list:
        - name: "I will praise you, Lord, for you have rescued me."
          book: RA
          priority: required
    offertory:
      list:
        - name: "Festival Canticle (This is the Feast)"
          book: BB
          priority: required
    communion:
      list:
        - name: "Worthy Is the Lamb"
          book: BB
          priority: required
    meditation:
      list:
        - name: "Christ is Arisen"
          composer: DeBruyn
          book: BB
          priority: preferred
    recessional:
      list:
        - name: "Join in the Dance"
          book: BB
          priority: preferred
    anthems:
      list:
        - name: "Simon, Son of God"
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
import yaml
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)

# Video links
with open('../../_hymns.yml', 'r') as vf:
    videos = yaml.safe_load(vf)
```

:::  {.red}
#### **Themes**
:::

Word/Eucharist, fulfillment, joy, hope, revelation, scripture, path of life, glory

:::  {.red}
#### **Entrance Antiphon**
:::

> Cry out with joy to God, all the earth;  
> O sing to the glory of his name.  
> O render him glorious praise, alleluia.

:::  {.red}
#### **Communion Antiphon**
:::

> The disciples recognized the Lord Jesus  
> in the breaking of the bread, alleluia.
>  
> [Or:]{.red}  
>   
> [Optional for Year B:]{.red}  
> The Christ had to suﬀer and on the third day rise from the dead;  
> in his name repentance and remission of sins  
> must be preached to all the nations, alleluia.  
>  
> [Or:]{.red}  
>  
> [Optional for Year C:]{.red}  
> Jesus said to his disciples: Come and eat.  
> And he took bread and gave it to them, alleluia.

::: {.titlered}
### &nbsp; Year A
:::
{{< var text.yeara >}}

```{python}
#| title: Year A
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['a'], urls=videos)
```

::: {.titlered}
### &nbsp; Year B
:::
{{< var text.yearb >}}

```{python}
#| title: Year B
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['b'], urls=videos)
```

::: {.titlered}
### &nbsp; Year C
:::
{{< var text.yearc >}}

```{python}
#| title: Year C
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['c'], urls=videos)
```


```{python}
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'], urls=videos)
```

::: {.red}
### Notes
:::

* If Mothers' Day falls on this week, “[On This Day, O Beautiful Mother](https://www.youtube.com/watch?v=Sn5sz5D67BY)” (BB) may be sung as a Meditation hymn.
