---
title: "Easter Sunday"
subtitle: "The Resurrection of the Lord"
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  abc:
    processional:
      list:
        - name: "Jesus Christ is Risen Today"
          book: BB
          priority: required
    psalm:
      list:
        - name: "This Day Was Made by the Lord"
          composer: Walker
          book: BB
          verses: "1-3 only"
          priority: optional
        - name: "Psalm 118: This is the Day"
          composer: "Joncas"
          book: BB
          priority: optional
    sequence:
      list:
        - name: "Christ, the Lord, Is Risen Today"
          tune: "VICTIMAE PASCHALI"
          book: BB
          priority: required
    offertory:
      list:
        - name: "Festival Canticle (This is the Feast)"
          book: BB
          priority: required
    communion:
      list:
        - name: "Worthy Is the Lamb"
          book: BB
          priority: required
    meditation:
      list:
        - name: "Be Joyful, Mary"
          book: BB
          priority: required
    recessional:
      list:
        - name: "The Strife is O'er"
          book: BB
          priority: required
  a:
    anthems:
      list:
        - name: "Proclaim the Message"
          composer: "Ricky Manalo"
  b:
    anthems:
      list:
        - name: "Thine Be the Glory"
  c:
    anthems:
      list:
        - name: "Hallelujah Chorus"
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
import yaml
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)

# Video links
with open('../../_hymns.yml', 'r') as vf:
    videos = yaml.safe_load(vf)
```

:::  {.red}
#### **Themes**
:::

solemnity, glory, joy, resurrection, life, hope, baptism

:::  {.red}
#### **Entrance Antiphon**
:::

> I have risen, and I am with you still, alleluia.  
> You have laid your hand upon me, alleluia.  
> Too wonderful for me, this knowledge, alleluia, alleluia.  
>  
> [Or:]{.red}  
>  
> The Lord is truly risen, alleluia.  
> To him be glory and power 
> for all the ages of eternity, alleluia, alleluia.

:::  {.red}
#### **Communion Antiphon**
:::

> Christ our Passover has been sacrificed, alleluia;  
> therefore let us keep the feast with the unleavened bread  
> of purity and truth, alleluia, alleluia.  

::: {.titlered}
### &nbsp; Year ABC
:::
{{< var text.yearabc >}}

```{python}
#| label: Year ABC
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['abc'], urls=videos)
```


```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'], urls=videos)
```

::: {.red}
### Notes
:::

* If available, the Festival Alleluia (GIA) is used for the **Gospel Acclamation** with the **Easter** verse found in [Appendix B](../appendices/B-festival-alleluia.qmd).
* The **Sequence** is sung by the cantor only (*i.e.*, no choir) immediately after the Second Reading. The entire hymn is to be sung. Note that it is the version set to the tune <span style="font-variant:small-caps">victimae paschali</span>. Accompaniment should be soft and reverent, like Meditation hymns.
* The **Regina Cæli** may be chanted (with light accompaniment) after Communion during the Easter Season if requested by the presider or if custom to the parish. It is not prescribed in the Liturgy.
* If the **dismissal of the people** is chanted by the presider, the cantor must promptly – without pause or hesitation – lead the chanted response found in [Appendix F](../appendices/F-easter-dismissal.qmd).