---
title: Vigil of Pentecost
subtitle: Extended Form
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  abc:
    psalm-after-first-reading:
      list:
        - name: "Blessed the people the Lord has chosen, chosen to be his own."
          book: BB
          priority: required
    psalm-after-second-reading:
      list:
        - name: "Glory and praise for ever!"
          book: RA
          priority: optional
        - name: "Lord, you have the words of everlasting life."
          book: RA
          priority: preferred          
    psalm-after-third-reading:
      list:
        - name: "Give thanks to the Lord; his love is everlasting."
          book: RA
          priority: required
    psalm-after-fourth-reading:
      list:
        - name: "Lord, send out your Spirit, and renewthe face of the earth."
          book: RA
          priority: required
    psalm-after-epistle:
      list:
        - name: "Alleluia, alleluia, alleluia"
          book: RA
          priority: optional
        - name: "Festival Alleluia"
          book: "Appendix B"
          note: "Pentecost verse"
          priority: preferred
    offertory:
      list:
        - name: "River of Glory"
          book: BB
          priority: optional
        - name: "O Breathe on Me, O Breath of God"
          book: BB
          priority: optional
    communion:
      list:
        - name: "Send Us Your Spirit, O Lord"
          book: BB
          priority: required
    meditation:
      list:
        - name: "Living Streams"
          book: BB
          note: "3x"
          priority: required
    recessional:
      list:
        - name: "One Spirit, One Church"
          book: BB
          priority: optional
        - name: "Hail Thee, Festival Day"
          verses: "5-6"
          priority: optional
    anthems:
      list:
        - name: "O How Amiable"
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
import yaml
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)

# Video links
with open('../../_hymns.yml', 'r') as vf:
    videos = yaml.safe_load(vf)
```

:::  {.red}
#### **Themes**
:::

light, language, the Spirit's imminence, renewal

:::  {.red}
#### **Entrance Antiphon**
:::

> The love of God has been poured into our hearts  
> through the Spirit of God dwelling within us, alleluia.

:::  {.red}
#### **Communion Antiphon**
:::

> On the last day of the festival, Jesus stood and cried out:  
> If anyone is thirsty, let him come to me and drink, alleluia.

::: {.titlered}
### &nbsp; Year ABC
:::
{{< var text.yearabc >}}

```{python}
#| title: Year ABC
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['abc'], urls=videos)
```


```{python}
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'], urls=videos)
```

::: {.red}
### Notes
:::

* If the **Extended Vigil** is not celebrated, two readings and one responsorial psalm can be used as usual. These are to be selected by the presider. The music minister should be sure to consult with the presider before the liturgy to know what psalm to sing.
* The presider may opt to use the same readings as Pentecost Sunday.
In this case, the music selections are taken from [Pentecost Sunday](pentecost.qmd), not from this list. The music minister must coordinate this with the presider before the start of the liturgy.
* If celebrated, the **Vigil of Pentecost** liturgy begins in the usual way
with the Processional hymn and Kyrie; however, the Gloria is not
sung until after the readings, as at the [**Easter Vigil**](../holy-week/easter-vigil.qmd).
* The Liturgy of the Word is organized just like at the [**Easter Vigil**](../holy-week/easter-vigil.qmd), with a series of readings, responsorial psalms, and prayers.
* After the prayer following the last reading and responsorial psalm, the
Celebrant intones the **Gloria** with “**Glory to God in the highest**” or
“*Gloria in excelsis Deo*.” The introduction can be started immediately
after this and the **Gloria** is sung as usual while the altar candles are lit.
* If available, the Festival Alleluia (GIA), with the **Pentecost** verse found in [Appendix B](../appendices/B-festival-alleluia.qmd), is sung for the **Gospel Acclamation**.
* If the **dismissal of the people** is chanted by the presider, the cantor
must promptly – without pause or hesitation – lead the chanted response
found in [Appendix F](../easter/pentecost-vigil.qmd).
* The hymn, “[Hail Thee, Festival Day](https://www.youtube.com/watch?v=cQvb8SN6RlU)”, could be considered as a
**Recessional hymn** if (1) it is available in the hymnal, (2) a strong choir and skilled musicians are performing at the **Vigil of Pentecost**, AND (3) the congregation is not likely to sing at this Liturgy. It is usually unfamiliar to Catholic congregations and is diﬃcult to sing; thus, it needs to be well rehearsed by choir, cantor, and musicians alike in order to be performed accurately and well. Nevertheless, it is a particularly festive hymn that is highly appropriate for this occasion. If used, the Pentecost verses (5-6) should be sung this night.