---
title: "SECOND SUNDAY IN ORDINARY TIME"
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  a:
    processional:
      list:
        - name: "All the Earth"
          book: BB
          priority: required
    psalm:
      list:
        - name: "Here I am, Lord; I come to do your will."
          book: RA
          priority: preferred
        - name: "Psalm 40: Here I Am"
          composer: Cooney
          book: BB
          priority: optional
    offertory:
      list:
        - name: "Here I Am, Lord"
          book: BB
          priority: required
    communion:
      list:
        - name: "Behold the Lamb"
          composer: Willett
          book: BB
          priority: required
    meditation:
      list:
        - name: "The Servant Song"
          book: BB
          priority: preferred
    recessional:
      list:
        - name: "Word of God, Come Down on Earth"
          book: BB
          priority: preferred
  b:
    processional:
      list:
        - name: "All the Earth"
          book: BB
          priority: required
    psalm:
      list:
        - name: "Here I am, Lord; I come to do your will."
          book: RA
          priority: preferred
        - name: "Psalm 40: Here I Am"
          composer: Cooney
          book: BB
          priority: optional
    offertory:
      list:
        - name: "Here I Am, Lord"
          book: BB
          priority: required
    communion:
      list:
        - name: "Behold the Lamb"
          composer: Willett
          book: BB
          priority: required
    meditation:
      list:
        - name: "Servant Song"
          book: BB
          priority: preferred
    recessional:
      list:
        - name: ""
          book: BB
  c:
    processional:
      list:
        - name: "All the Earth"
          book: BB
          priority: optional
        - name: "Come to the Feast"
          book: BB
          priority: optional
    psalm:
      list:
        - name: "Proclaim his marvelous deeds to all the nations."
          book: RA
          priority: required
    offertory:
      list:
        - name: "We Are Many Parts"
          book: BB
          priority: required
    communion:
      list:
        - name: "The Supper of the Lord"
          book: BB
          priority: required
    meditation:
      list:
        - name: "What Feast of Love"
          book: BB
          priority: required
    recessional:
      list:
        - name: ""
          book: BB
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
import yaml
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)

# Video links
with open('../../_hymns.yml', 'r') as vf:
    videos = yaml.safe_load(vf)
```

:::  {.red}
#### **Themes**
:::

[Year A:]{.red} Lamb of God, witness, service  
[Year B:]{.red} the call of God, receptivity, discipleship, Lamb of
God, obedience  
[Year C:]{.red} revealed glory, manifestation, marriage, miracle  

:::  {.red}
#### **Entrance Antiphon**
:::

> All the earth shall bow down before you, O God,  
> and shall sing to you,  
> shall sing to your name, O Most High!

:::  {.red}
#### **Communion Antiphon**
:::

> You have prepared a table before me,  
> and how precious is the chalice that quenches my thirst.  
>  
> [Or:]{.red}  
>  
> We have come to know and to believe  
> in the love that God has for us.

:::: {.content-visible when-format="html"}
::: {.red}
### Readings
:::

<details>
  <summary>Click to view the readings for this liturgy.</summary>

::: {.red}
### &nbsp; Year A

#### First Reading [Isaiah 49:3, 5-6]{style="float:right" .small}
:::

The LORD said to me: You are my servant,  
Israel, through whom I show my glory.  
Now the LORD has spoken  
who formed me as his servant from the womb,  
that Jacob may be brought back to him  
and Israel gathered to him;  
and I am made glorious in the sight of the LORD,  
and my God is now my strength!  
It is too little, the LORD says, for you to be my servant,  
to raise up the tribes of Jacob,  
and restore the survivors of Israel;  
I will make you a light to the nations,  
that my salvation may reach to the ends of the earth.

***

::: {.red}
#### Responsorial Psalm [Psalm 40:2, 4, 7-8, 8-9, 10]{style="float:right" .small}
:::

**[℟.]{.red}** **Here am I, Lord; I come to do your will.**  

I have waited, waited for the LORD,  
and he stooped toward me and heard my cry.  
And he put a new song into my mouth,  
a hymn to our God. **[℟.]{.red}**  

Sacrifice or offering you wished not,  
but ears open to obedience you gave me.  
Holocausts or sin-offerings you sought not;  
then said I, "Behold I come." **[℟.]{.red}**  

"In the written scroll it is prescribed for me,  
to do your will, O my God, is my delight,  
and your law is within my heart!" **[℟.]{.red}**  

I announced your justice in the vast assembly;  
I did not restrain my lips, as you, O LORD, know.  
R/ Here am I, Lord; I come to do your will. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [1 Corinthians 1:1-3]{style="float:right" .small}
:::

Paul, called to be an apostle of Christ Jesus by the will of God,  
and Sosthenes our brother,  
to the church of God that is in Corinth,  
to you who have been sanctified in Christ Jesus, called to be holy,  
with all those everywhere who call upon the name of our Lord Jesus Christ, their Lord and ours.  
Grace to you and peace from God our Father  
and the Lord Jesus Christ.  

***

::: {.red}
#### Gospel Acclamation [John 1:14a, 12a]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
The Word of God became flesh and dwelt among us.  
To those who accepted him,  
he gave power to become children of God. **[℟.]{.red}**

***

::: {.red}
#### Gospel [John 1:29-34]{style="float:right" .small}
:::

John the Baptist saw Jesus coming toward him and said,  
"Behold, the Lamb of God, who takes away the sin of the world.  
He is the one of whom I said,  
'A man is coming after me who ranks ahead of me  
because he existed before me.'  
I did not know him,  
but the reason why I came baptizing with water  
was that he might be made known to Israel."  
John testified further, saying,  
"I saw the Spirit come down like a dove from heaven  
and remain upon him.  
I did not know him,  
but the one who sent me to baptize with water told me,  
'On whomever you see the Spirit come down and remain,  
he is the one who will baptize with the Holy Spirit.'  
Now I have seen and testified that he is the Son of God."

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

::: {.red}
### &nbsp; Year B

#### First Reading [1 Samuel 3:3b-10, 19]{style="float:right" .small}
:::

Samuel was sleeping in the temple of the LORD  
where the ark of God was.  
The LORD called to Samuel, who answered, "Here I am."  
Samuel ran to Eli and said, "Here I am. You called me."  
"I did not call you, " Eli said. "Go back to sleep."  
So he went back to sleep.  
Again the LORD called Samuel, who rose and went to Eli.  
"Here I am, " he said. "You called me."  
But Eli answered, "I did not call you, my son. Go back to sleep."  

At that time Samuel was not familiar with the LORD,  
because the LORD had not revealed anything to him as yet.  
The LORD called Samuel again, for the third time.  
Getting up and going to Eli, he said, "Here I am. You called me."  
Then Eli understood that the LORD was calling the youth.  
So he said to Samuel, "Go to sleep, and if you are called, reply,  
Speak, LORD, for your servant is listening."  
When Samuel went to sleep in his place,  
the LORD came and revealed his presence,  
calling out as before, "Samuel, Samuel!"  
Samuel answered, "Speak, for your servant is listening."  

Samuel grew up, and the LORD was with him,  
not permitting any word of his to be without effect.

***

::: {.red}
#### Responsorial Psalm [Psalm 40:2, 4, 7-8, 8-9, 10]{style="float:right" .small}
:::

**[℟.]{.red}** **Here am I, Lord; I come to do your will.**  

I have waited, waited for the LORD,  
and he stooped toward me and heard my cry.  
And he put a new song into my mouth,  
a hymn to our God. **[℟.]{.red}**  

Sacrifice or offering you wished not,  
but ears open to obedience you gave me.  
Holocausts or sin-offerings you sought not;  
then said I, "Behold I come." **[℟.]{.red}**  

"In the written scroll it is prescribed for me,  
to do your will, O my God, is my delight,  
and your law is within my heart!" **[℟.]{.red}**  

I announced your justice in the vast assembly;  
I did not restrain my lips, as you, O LORD, know. **[℟.]{.red}**

***

::: {.red}
#### Second Reading [1 Corinthians 6:13c-15a, 17-20]{style="float:right" .small}
:::

Brothers and sisters:  
The body is not for immorality, but for the Lord,  
and the Lord is for the body;  
God raised the Lord and will also raise us by his power.  

Do you not know that your bodies are members of Christ?  
But whoever is joined to the Lord becomes one Spirit with him.  
Avoid immorality.  
Every other sin a person commits is outside the body,  
but the immoral person sins against his own body.  
Do you not know that your body  
is a temple of the Holy Spirit within you,  
whom you have from God, and that you are not your own?  
For you have been purchased at a price.  
Therefore glorify God in your body.  

***

::: {.red}
#### Gospel Acclamation [John 1:41, 17b]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
We have found the Messiah:  
Jesus Christ, who brings us truth and grace. **[℟.]{.red}**  

***

::: {.red}
#### Gospel [John 1:35-42]{style="float:right" .small}
:::

John was standing with two of his disciples,  
and as he watched Jesus walk by, he said,  
"Behold, the Lamb of God."  
The two disciples heard what he said and followed Jesus.  
Jesus turned and saw them following him and said to them,  
"What are you looking for?"  
They said to him, "Rabbi" — which translated means Teacher —,  
"where are you staying?"  
He said to them, "Come, and you will see."  
So they went and saw where Jesus was staying,  
and they stayed with him that day.  
It was about four in the afternoon.  
Andrew, the brother of Simon Peter,  
was one of the two who heard John and followed Jesus.  
He first found his own brother Simon and told him,  
"We have found the Messiah" — which is translated Christ —.  
Then he brought him to Jesus.  
Jesus looked at him and said,  
"You are Simon the son of John;  
you will be called Cephas" — which is translated Peter.  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

::: {.red}
### &nbsp; Year C

#### First Reading [Isaiah 62:1-5]{style="float:right" .small}
:::

For Zion’s sake I will not be silent,  
&emsp; for Jerusalem’s sake I will not be quiet,  
until her vindication shines forth like the dawn  
&emsp; and her victory like a burning torch.  

Nations shall behold your vindication,  
&emsp; and all the kings your glory;  
you shall be called by a new name  
&emsp; pronounced by the mouth of the LORD.  
You shall be a glorious crown in the hand of the LORD,  
&emsp; a royal diadem held by your God.  
No more shall people call you “Forsaken,“  
&emsp; or your land “Desolate,“  
but you shall be called “My Delight,“  
&emsp; and your land “Espoused.”  
For the LORD delights in you  
&emsp; and makes your land his spouse.  
As a young man marries a virgin,  
&emsp; your Builder shall marry you;  
and as a bridegroom rejoices in his bride  
&emsp; so shall your God rejoice in you.  

***

::: {.red}
#### Responsorial Psalm [Psalm 96:1-2, 2-3, 7-8, 9-10]{style="float:right" .small}
:::

**[℟.]{.red}** **Proclaim his marvelous deeds to all the nations.**  

Sing to the LORD a new song;  
&emsp; sing to the LORD, all you lands.  
Sing to the LORD; bless his name. **[℟.]{.red}**  

Announce his salvation, day after day.  
Tell his glory among the nations;  
&emsp; among all peoples, his wondrous deeds. **[℟.]{.red}**  

Give to the LORD, you families of nations,  
&emsp; give to the LORD glory and praise;  
&emsp; give to the LORD the glory due his name! **[℟.]{.red}**  

Worship the LORD in holy attire.  
&emsp; Tremble before him, all the earth;  
Say among the nations: The LORD is king.  
&emsp; He governs the peoples with equity. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [1 Corinthians 12:4-11]{style="float:right" .small}
:::

Brothers and sisters:  
There are different kinds of spiritual gifts but the same Spirit;  
there are different forms of service but the same Lord;  
there are different workings but the same God  
who produces all of them in everyone.  
To each individual the manifestation of the Spirit  
is given for some benefit.  
To one is given through the Spirit the expression of wisdom;  
to another, the expression of knowledge according to the 
same Spirit;  
to another, faith by the same Spirit;  
to another, gifts of healing by the one Spirit;  
to another, mighty deeds;  
to another, prophecy;  
to another, discernment of spirits;  
to another, varieties of tongues;  
to another, interpretation of tongues.  
But one and the same Spirit produces all of these,  
distributing them individually to each person as he wishes.  

***

::: {.red}
#### Gospel Acclamation [2 Thessalonians 2:14]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
God has called us through the Gospel  
to possess the glory of our Lord Jesus Christ. **[℟.]{.red}** 

***

::: {.red}
#### Gospel [John 2:1-11]{style="float:right" .small}
:::

There was a wedding at Cana in Galilee,  
and the mother of Jesus was there.  
Jesus and his disciples were also invited to the wedding.  
When the wine ran short,  
the mother of Jesus said to him,  
“They have no wine.”  
And Jesus said to her,  
“Woman, how does your concern affect me?  
My hour has not yet come.”  
His mother said to the servers,  
“Do whatever he tells you.”  
Now there were six stone water jars there for Jewish ceremonial washings,  
each holding twenty to thirty gallons.  
Jesus told them,  
“Fill the jars with water.”  
So they filled them to the brim.  
Then he told them,  
“Draw some out now and take it to the headwaiter.”  
So they took it.   
And when the headwaiter tasted the water that had become wine,  
without knowing where it came from  
— although the servers who had drawn the water knew —,  
the headwaiter called the bridegroom and said to him,  
“Everyone serves good wine first,  
and then when people have drunk freely, an inferior one;  
but you have kept the good wine until now.”  
Jesus did this as the beginning of his signs at Cana in Galilee  
and so revealed his glory,  
and his disciples began to believe in him.

</details>
::::

::: {.red}
## Music Selections
:::

::: {.titlered}
### &nbsp; Year A
:::
{{< var text.yeara >}}

```{python}
#| label: Year A
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['a'], urls=videos)
```

::: {.titlered}
### &nbsp; Year B
:::
{{< var text.yearb >}}

```{python}
#| label: Year B
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['b'], urls=videos)
```

::: {.titlered}
### &nbsp; Year C
:::
{{< var text.yearc >}}

```{python}
#| label: Year C
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['c'], urls=videos)
```


```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'], urls=videos)
```

::: {.red}
### Notes
:::

* “Servant Song” and “The Servant Song” are two diﬀerent songs.