---
title: "THIRD SUNDAY IN ORDINARY TIME"
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  a:
    processional:
      list:
        - name: "Sing a New Song"
          book: BB
          priority: required
    psalm:
      list:
        - name: "The Lord is my light and my salvation."
          book: RA
          priority: required
    offertory:
      list:
        - name: "Lord, You Have Come to the Seashore"
          book: BB
          note: English; see note below
          priority: required
    communion:
      list:
        - name: "I Know that My Redeemer Lives"
          composer: Soper
          book: BB
          priority: required
    meditation:
      list:
        - name: "The Lord Is My Light"
          composer: Walker
          book: BB
          priority: required
    recessional:
      list:
        - name: "City of God"
          book: BB
          priority: required
  b:
    processional:
      list:
        - name: "Sing a New Song"
          book: BB
          priority: required
    psalm:
      list:
        - name: "Teach me your ways, O Lord."
          book: RA
          priority: required
    offertory:
      list:
        - name: "The Summons"
          book: BB
          priority: preferred
    communion:
      list:
        - name: "Lord, You Have Come to the Seashore"
          book: BB
          note: English; see note below
          priority: required
    meditation:
      list:
        - name: "Remember Your Love"
          book: BB
          priority: required
    recessional:
      list:
        - name: ""
          book: BB
  c:
    processional:
      list:
        - name: "Sing a New Song"
          book: BB
          priority: required
    psalm:
      list:
        - name: "Your words, Lord, are Spirit and life."
          book: RA
          priority: preferred
        - name: "Your Words Are Spirit and Life"
          composer: Farrell
          book: BB
          priority: optional
    offertory:
      list:
        - name: "One Bread, One Body"
          book: BB
          priority: required
    communion:
      list:
        - name: "One Love Released"
          book: BB
          priority: required
    meditation:
      list:
        - name: "We Are Many Parts"
          book: BB
          priority: required
    recessional:
      list:
        - name: "Praise to You, O Christ, Our Savior"
          book: BB
          priority: preferred
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
import yaml
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)

# Video links
with open('../../_hymns.yml', 'r') as vf:
    videos = yaml.safe_load(vf)
```

:::  {.red}
#### **Themes**
:::

[Year A:]{.red} unity, light, discipleship, joy, protection, healing  
[Year B:]{.red} forgiveness, repentance, mercy, kingdom of God,
metanoia, proclamation of the Good News  
[Year C:]{.red} unity, fulfillment  

:::  {.red}
#### **Entrance Antiphon**
:::

> O sing a new song to the Lord;  
> sing to the Lord, all the earth.  
> In his presence are majesty and splendor,  
> strength and honor in his holy place.

:::  {.red}
#### **Communion Antiphon**
:::

> Look toward the Lord and be radiant;  
> let your faces not be ashamed. 
>  
> [Or:]{.red}  
>  
> I am the light of the world, says the Lord;  
> whoever follows me will not walk in darkness,  
> but will have the light of life.

:::: {.content-visible when-format="html"}
::: {.red}
### Readings
:::

<details>
  <summary>Click to view the readings for this liturgy.</summary>

::: {.red}
### &nbsp; Year A

#### First Reading [Isaiah 8:23—9:3]{style="float:right" .small}
:::

First the Lord degraded the land of Zebulun  
and the land of Naphtali;  
but in the end he has glorified the seaward road,  
the land west of the Jordan,  
the District of the Gentiles.  

Anguish has taken wing, dispelled is darkness:  
for there is no gloom where but now there was distress.  
The people who walked in darkness  
have seen a great light;  
upon those who dwelt in the land of gloom  
a light has shone.  
You have brought them abundant joy  
and great rejoicing,  
as they rejoice before you as at the harvest,  
as people make merry when dividing spoils.  
For the yoke that burdened them,  
the pole on their shoulder,  
and the rod of their taskmaster  
you have smashed, as on the day of Midian.

***

::: {.red}
#### Responsorial Psalm [Psalm 27:1, 4, 13-14]{style="float:right" .small}
:::

**[℟.]{.red}** **The Lord is my light and my salvation.**  

The LORD is my light and my salvation;  
whom should I fear?  
The LORD is my life’s refuge;  
of whom should I be afraid? **[℟.]{.red}**  

One thing I ask of the LORD;  
this I seek:  
To dwell in the house of the LORD  
all the days of my life,  
That I may gaze on the loveliness of the LORD  
and contemplate his temple. **[℟.]{.red}**  

I believe that I shall see the bounty of the LORD  
in the land of the living.  
Wait for the LORD with courage;  
be stouthearted, and wait for the LORD. **[℟.]{.red}**

***

::: {.red}
#### Second Reading [1 Corinthians 1:10-13, 17]{style="float:right" .small}
:::

I urge you, brothers and sisters, in the name of our Lord Jesus Christ,  
that all of you agree in what you say,  
and that there be no divisions among you,  
but that you be united in the same mind and in the same purpose.  
For it has been reported to me about you, my brothers and sisters,  
by Chloe’s people, that there are rivalries among you.  
I mean that each of you is saying,  
“I belong to Paul,” or “I belong to Apollos,”  
or “I belong to Cephas,” or “I belong to Christ.”  
Is Christ divided?  
Was Paul crucified for you?  
Or were you baptized in the name of Paul?  
For Christ did not send me to baptize but to preach the gospel,  
and not with the wisdom of human eloquence,  
so that the cross of Christ might not be emptied of its meaning.

***

::: {.red}
#### Alleluia [Matthew 4:23]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
Jesus proclaimed the Gospel of the kingdom  
and cured every disease among the people. **[℟.]{.red}**

***

::: {.red}
#### Gospel [Matthew 4:12-23 or 4:12-17]{style="float:right" .small}
:::

When Jesus heard that John had been arrested,  
he withdrew to Galilee.  
He left Nazareth and went to live in Capernaum by the sea,  
in the region of Zebulun and Naphtali,  
that what had been said through Isaiah the prophet  
might be fulfilled:  
*Land of Zebulun and land of Naphtali,*  
*the way to the sea, beyond the Jordan,*  
*Galilee of the Gentiles,*  
*the people who sit in darkness have seen a great light,*  
*on those dwelling in a land overshadowed by death*  
*light has arisen.*  
From that time on, Jesus began to preach and say,  
“Repent, for the kingdom of heaven is at hand.”  

As he was walking by the Sea of Galilee, he saw two brothers,  
Simon who is called Peter, and his brother Andrew,  
casting a net into the sea; they were fishermen.  
He said to them,  
“Come after me, and I will make you fishers of men.”  
At once they left their nets and followed him.  
He walked along from there and saw two other brothers,  
James, the son of Zebedee, and his brother John.  
They were in a boat, with their father Zebedee, mending their nets.  
He called them, and immediately they left their boat and their father
and followed him.
He went around all of Galilee,  
teaching in their synagogues, proclaiming the gospel of the kingdom,  
and curing every disease and illness among the people.

[Or:]{.red}

When Jesus heard that John had been arrested,  
he withdrew to Galilee.  
He left Nazareth and went to live in Capernaum by the sea,  
in the region of Zebulun and Naphtali,  
that what had been said through Isaiah the prophet  
might be fulfilled:  
*Land of Zebulun and land of Naphtali,*  
*the way to the sea, beyond the Jordan,*  
*Galilee of the Gentiles,*  
*the people who sit in darkness have seen a great light,*  
*on those dwelling in a land overshadowed by death*  
*light has arisen.*  
From that time on, Jesus began to preach and say,  
“Repent, for the kingdom of heaven is at hand.”

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

::: {.red}
### &nbsp; Year B

#### First Reading [Jonah 3:1-5, 10]{style="float:right" .small}
:::

The word of the LORD came to Jonah, saying:  
"Set out for the great city of Nineveh,  
and announce to it the message that I will tell you."  
So Jonah made ready and went to Nineveh,  
according to the LORD'S bidding.  
Now Nineveh was an enormously large city;  
it took three days to go through it.  
Jonah began his journey through the city,  
and had gone but a single day's walk announcing,  
"Forty days more and Nineveh shall be destroyed,"  
when the people of Nineveh believed God;  
they proclaimed a fast  
and all of them, great and small, put on sackcloth.  

When God saw by their actions how they turned from their evil way,  
he repented of the evil that he had threatened to do to them;  
he did not carry it out.

***

::: {.red}
#### Responsorial Psalm [Psalm 25:4-5, 6-7, 8-9]{style="float:right" .small}
:::

**[℟.]{.red}** **Teach me your ways, O Lord.**  

Your ways, O LORD, make known to me;  
teach me your paths,  
Guide me in your truth and teach me,  
for you are God my savior.  **[℟.]{.red}**  

Remember that your compassion, O LORD,  
and your love are from of old.  
In your kindness remember me,  
because of your goodness, O LORD. **[℟.]{.red}**  

Good and upright is the LORD;  
thus he shows sinners the way.  
He guides the humble to justice  
and teaches the humble his way. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [1 Corinthians 7:29-31]{style="float:right" .small}
:::

I tell you, brothers and sisters, the time is running out.  
From now on, let those having wives act as not having them,  
those weeping as not weeping,  
those rejoicing as not rejoicing,  
those buying as not owning,  
those using the world as not using it fully.  
For the world in its present form is passing away.

***

::: {.red}
#### Alleluia [Mark 1:15]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
The kingdom of God is at hand.  
Repent and believe in the Gospel. **[℟.]{.red}**  

***

::: {.red}
#### Gospel [Mark 1:14-20]{style="float:right" .small}
:::

After John had been arrested,  
Jesus came to Galilee proclaiming the gospel of God:  
"This is the time of fulfillment.  
The kingdom of God is at hand.  
Repent, and believe in the gospel."  

As he passed by the Sea of Galilee,  
he saw Simon and his brother Andrew casting their nets into the sea;  
they were fishermen.  
Jesus said to them,  
"Come after me, and I will make you fishers of men."  
Then they abandoned their nets and followed him.  
He walked along a little farther  
and saw James, the son of Zebedee, and his brother John.  
They too were in a boat mending their nets.  
Then he called them.  
So they left their father Zebedee in the boat  
along with the hired men and followed him.

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

::: {.red}
### &nbsp; Year C

#### First Reading [Nehemiah 8:2-4a, 5-6, 8-10]{style="float:right" .small}
:::

Ezra the priest brought the law before the assembly,  
which consisted of men, women,  
and those children old enough to understand.  
Standing at one end of the open place that was before the Water Gate,  
he read out of the book from daybreak till midday,  
in the presence of the men, the women,  
and those children old enough to understand;  
and all the people listened attentively to the book of the law.  
Ezra the scribe stood on a wooden platform  
that had been made for the occasion.  
He opened the scroll  
so that all the people might see it  
— for he was standing higher up than any of the people —;  
and, as he opened it, all the people rose.  
Ezra blessed the LORD, the great God,  
and all the people, their hands raised high, answered,  
"Amen, amen!"  
Then they bowed down and prostrated themselves before the LORD,  
their faces to the ground.  
Ezra read plainly from the book of the law of God,  
interpreting it so that all could understand what was read.  
Then Nehemiah, that is, His Excellency, and Ezra the priest-scribe  
and the Levites who were instructing the people  
said to all the people:  
"Today is holy to the LORD your God.  
Do not be sad, and do not weep"—  
for all the people were weeping as they heard the words of the law.  
He said further: "Go, eat rich foods and drink sweet drinks,  
and allot portions to those who had nothing prepared;  
for today is holy to our LORD.  
Do not be saddened this day,  
for rejoicing in the LORD must be your strength!"

***

::: {.red}
#### Responsorial Psalm [Psalm 19:8, 9, 10, 15; cf John 6:63c]{style="float:right" .small}
:::

**[℟.]{.red}** **Your words, Lord, are Spirit and life.**  

The law of the LORD is perfect,  
refreshing the soul;  
The decree of the LORD is trustworthy,  
giving wisdom to the simple. **[℟.]{.red}** 

The precepts of the LORD are right,  
rejoicing the heart;  
The command of the LORD is clear,  
enlightening the eye. **[℟.]{.red}** 

The fear of the LORD is pure,  
enduring forever;  
The ordinances of the LORD are true,  
all of them just. **[℟.]{.red}** 

Let the words of my mouth and the thought of my heart  
find favor before you,  
O LORD, my rock and my redeemer. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [1 Corinthians 12:12-30 or 12:12-14, 27]{style="float:right" .small}
:::

Brothers and sisters:  
As a body is one though it has many parts,  
and all the parts of the body, though many, are one body,  
so also Christ.  
For in one Spirit we were all baptized into one body,  
whether Jews or Greeks, slaves or free persons,  
and we were all given to drink of one Spirit.  

Now the body is not a single part, but many.  
If a foot should say,  
"Because I am not a hand I do not belong to the body,"  
it does not for this reason belong any less to the body.  
Or if an ear should say,  
"Because I am not an eye I do not belong to the body,"

it does not for this reason belong any less to the body.  
If the whole body were an eye, where would the hearing be?  
If the whole body were hearing, where would the sense of smell be?  
But as it is, God placed the parts,  
each one of them, in the body as he intended.  
If they were all one part, where would the body be?  
But as it is, there are many parts, yet one body.  
The eye cannot say to the hand, "I do not need you,"  
nor again the head to the feet, "I do not need you."  
Indeed, the parts of the body that seem to be weaker  
are all the more necessary,  
and those parts of the body that we consider less honorable  
we surround with greater honor,  
and our less presentable parts are treated with greater propriety,  
whereas our more presentable parts do not need this.  
But God has so constructed the body  
as to give greater honor to a part that is without it,  
so that there may be no division in the body,  
but that the parts may have the same concern for one another.  
If one part suffers, all the parts suffer with it;  
if one part is honored, all the parts share its joy.  

Now you are Christ's body, and individually parts of it.  
Some people God has designated in the church  
to be, first, apostles; second, prophets; third, teachers;  
then, mighty deeds;  
then gifts of healing, assistance, administration,  
and varieties of tongues.  
Are all apostles? Are all prophets? Are all teachers?  
Do all work mighty deeds? Do all have gifts of healing?  
Do all speak in tongues? Do all interpret?

[Or:]{.red}

Brothers and sisters:  
As a body is one though it has many parts,  
and all the parts of the body, though many, are one body,  
so also Christ.  
For in one Spirit we were all baptized into one body,  
whether Jews or Greeks, slaves or free persons,

and we were all given to drink of one Spirit.  
Now the body is not a single part, but many.  
You are Christ's body, and individually parts of it.

***

::: {.red}
#### Alleluia [Cf. Luke 4:18]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
The Lord sent me to bring glad tidings to the poor,  
and to proclaim liberty to captives. **[℟.]{.red}** 

***

::: {.red}
#### Gospel [Luke 1:1-4; 4:14-21]{style="float:right" .small}
:::

Since many have undertaken to compile a narrative of the events  
that have been fulfilled among us,  
just as those who were eyewitnesses from the beginning  
and ministers of the word have handed them down to us,  
I too have decided,  
after investigating everything accurately anew,  
to write it down in an orderly sequence for you,  
most excellent Theophilus,  
so that you may realize the certainty of the teachings  
you have received.  

Jesus returned to Galilee in the power of the Spirit,  
and news of him spread throughout the whole region.  
He taught in their synagogues and was praised by all.  

He came to Nazareth, where he had grown up,  
and went according to his custom  
into the synagogue on the sabbath day.  
He stood up to read and was handed a scroll of the prophet Isaiah.  
He unrolled the scroll and found the passage where it was written:  
*The Spirit of the Lord is upon me,*  
*because he has anointed me*  
*to bring glad tidings to the poor.*  
*He has sent me to proclaim liberty to captives*  
*and recovery of sight to the blind,*  
*to let the oppressed go free,*  
*and to proclaim a year acceptable to the Lord.*  
Rolling up the scroll, he handed it back to the attendant and sat down,  
and the eyes of all in the synagogue looked intently at him.  
He said to them,  
"Today this Scripture passage is fulfilled in your hearing."

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

</details>
::::

::: {.red}
## Music Selections
:::

::: {.titlered}
### &nbsp; Year A
:::
{{< var text.yeara >}}

```{python}
#| label: Year A
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['a'], urls=videos)
```

::: {.titlered}
### &nbsp; Year B
:::
{{< var text.yearb >}}

```{python}
#| label: Year B
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['b'], urls=videos)
```

::: {.titlered}
### &nbsp; Year C
:::
{{< var text.yearc >}}

```{python}
#| label: Year C
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['c'], urls=videos)
```


```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'], urls=videos)
```

::: {.red}
### Notes
:::

* BB (OCP) calls this song “Lord, You Have Come to the Seashore,” while GIA calls it “Lord, When You Came to the Seashore.” The English GIA lyrics are preferred over those in BB, if given the option.