---
title: "FOURTH SUNDAY IN ORDINARY TIME"
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  a:
    processional:
      list:
        - name: "Gather Us In"
          book: BB
          priority: required
    psalm:
      list:
        - name: "Blessed are the poor in spirit; the kingdom of heaven is theirs!"
          book: RA
          priority: required
    offertory:
      list:
        - name: "We Are the Light of the World"
          book: BB
          priority: required
    communion:
      list:
        - name: "Seek Ye First"
          book: BB
          priority: required
    meditation:
      list:
        - name: "Rejoice in the Promise of Jesus"
          book: BB
          priority: required
    recessional:
      list:
        - name: "Lead Me, Lord"
          book: BB
          priority: required
  b:
    processional:
      list:
        - name: "Gather Your People"
          book: BB
          priority: required
    psalm:
      list:
        - name: "If today you hear his voice, harden not your hearts."
          book: RA
          priority: required
    offertory:
      list:
        - name: ""
          book: BB
    communion:
      list:
        - name: ""
          book: BB
    meditation:
      list:
        - name: "Healing River of the Spirit"
          book: BB
          priority: required
    recessional:
      list:
        - name: "City of God"
          book: BB
          priority: preferred
  c:
    processional:
      list:
        - name: "Gather the People"
          book: BB
          priority: required
    psalm:
      list:
        - name: "I will sing of your salvation."
          book: RA
          priority: required
    offertory:
      list:
        - name: "O God, You Search Me"
          book: BB
          priority: required
    communion:
      list:
        - name: ""
          book: BB
    meditation:
      list:
        - name: ""
          book: BB
    recessional:
      list:
        - name: "Love Divine, All Loves Excelling"
          book: BB
          priority: required
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
import yaml
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)

# Video links
with open('../../_hymns.yml', 'r') as vf:
    videos = yaml.safe_load(vf)
```

:::  {.red}
#### **Themes**
:::

[Year A:]{.red} humility, kingdom of God, heaven, wisdom  
[Year B:]{.red} authority of Christ, healing, power of God  
[Year C:]{.red} love, universality, Christ's presence, prophecy  

:::  {.red}
#### **Entrance Antiphon**
:::

> Save us, O Lord our God!  
> And gather us from the nations,  
> to give thanks to your holy name,  
> and make it our glory to praise you.

:::  {.red}
#### **Communion Antiphon**
:::

> Let your face shine on your servant.  
> Save me in your merciful love.  
> O Lord, let me never be put to shame, for I call to you.  
> 
> [Or:]{.red}  
>  
> Blessed are the poor in spirit,  
> for theirs is the Kingdom of Heaven.  
> Blessed are the meek, for they shall possess the land.

:::: {.content-visible when-format="html"}
::: {.red}
### Readings
:::

<details>
  <summary>Click to view the readings for this liturgy.</summary>

::: {.red}
### &nbsp; Year A

#### First Reading [Zephaniah 2:3; 3:12-13]{style="float:right" .small}
:::

Seek the LORD, all you humble of the earth,  
who have observed his law;  
seek justice, seek humility;  
perhaps you may be sheltered  
on the day of the LORD's anger.  

But I will leave as a remnant in your midst  
a people humble and lowly,  
who shall take refuge in the name of the LORD:  
the remnant of Israel.  
They shall do no wrong  
and speak no lies;  
nor shall there be found in their mouths  
a deceitful tongue;  
they shall pasture and couch their flocks  
with none to disturb them.  

***

::: {.red}
#### Responsorial Psalm [Psalm 146:6-7, 8-9, 9-10; Mt 5:3]{style="float:right" .small}
:::

**[℟.]{.red}** **Blessed are the poor in spirit; the kingdom of heaven is theirs!**  
[Or:]{.red}  
**[℟.]{.red}** **Alleluia.**  

The LORD keeps faith forever,  
secures justice for the oppressed,  
gives food to the hungry.  
The LORD sets captives free. **[℟.]{.red}**  

The LORD gives sight to the blind;  
the LORD raises up those who were bowed down.  
The LORD loves the just;  
the LORD protects strangers. **[℟.]{.red}**  

The fatherless and the widow the LORD sustains,  
but the way of the wicked he thwarts.  
The LORD shall reign forever;  
your God, O Zion, through all generations. Alleluia. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [1 Corinthians 1:26-31]{style="float:right" .small}
:::

Consider your own calling, brothers and sisters.  
Not many of you were wise by human standards,  
not many were powerful,  
not many were of noble birth.  
Rather, God chose the foolish of the world to shame the wise,  
and God chose the weak of the world to shame the strong,  
and God chose the lowly and despised of the world,  
those who count for nothing,  
to reduce to nothing those who are something,  
so that no human being might boast before God.  
It is due to him that you are in Christ Jesus,  
who became for us wisdom from God,  
as well as righteousness, sanctification, and redemption,  
so that, as it is written,  
"Whoever boasts, should boast in the Lord."

***

::: {.red}
#### Gospel Acclamation [Matthew 5:12a]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
Rejoice and be glad;  
your reward will be great in heaven. **[℟.]{.red}**

***

::: {.red}
#### Gospel [Matthew 5:1-12a]{style="float:right" .small}
:::

When Jesus saw the crowds, he went up the mountain,  
and after he had sat down, his disciples came to him.   
He began to teach them, saying:  
"Blessed are the poor in spirit,  
for theirs is the kingdom of heaven.  
Blessed are they who mourn,  
for they will be comforted.  
Blessed are the meek,  
for they will inherit the land.  
Blessed are they who hunger and thirst for righteousness,  
for they will be satisfied.  
Blessed are the merciful,  
for they will be shown mercy.  
Blessed are the clean of heart,  
for they will see God.  
Blessed are the peacemakers,  
for they will be called children of God.  
Blessed are they who are persecuted for the sake of righteousness,  
for theirs is the kingdom of heaven.  
Blessed are you when they insult you and persecute you  
and utter every kind of evil against you falsely because of me.  
Rejoice and be glad,  
for your reward will be great in heaven."

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

::: {.red}
### &nbsp; Year B

#### First Reading [Deuteronomy 18:15-20]{style="float:right" .small}
:::

Moses spoke to all the people, saying:  
"A prophet like me will the LORD, your God, raise up for you  
from among your own kin;  
to him you shall listen.  
This is exactly what you requested of the LORD, your God, at Horeb  
on the day of the assembly, when you said,  
'Let us not again hear the voice of the LORD, our God,  
nor see this great fire any more, lest we die.'  
And the LORD said to me, 'This was well said.  
I will raise up for them a prophet like you from among their kin,  
and will put my words into his mouth;  
he shall tell them all that I command him.  
Whoever will not listen to my words which he speaks in my name,  
I myself will make him answer for it.  
But if a prophet presumes to speak in my name  
an oracle that I have not commanded him to speak,  
or speaks in the name of other gods, he shall die.'"

***

::: {.red}
#### Responsorial Psalm [Psalm 95:1-2, 6-7, 7-9]{style="float:right" .small}
:::

**[℟.]{.red}** **If today you hear his voice, harden not your hearts.**  

Come, let us sing joyfully to the LORD;  
let us acclaim the rock of our salvation.  
Let us come into his presence with thanksgiving;  
let us joyfully sing psalms to him. **[℟.]{.red}**  

Come, let us bow down in worship;  
let us kneel before the LORD who made us.  
For he is our God,  
and we are the people he shepherds, the flock he guides. **[℟.]{.red}**  

Oh, that today you would hear his voice:  
"Harden not your hearts as at Meribah,  
as in the day of Massah in the desert,  
Where your fathers tempted me;  
they tested me though they had seen my works." **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [1 Corinthians 7:32-35]{style="float:right" .small}
:::

Brothers and sisters:  
I should like you to be free of anxieties.  
An unmarried man is anxious about the things of the Lord,  
how he may please the Lord.  
But a married man is anxious about the things of the world,  
how he may please his wife, and he is divided.  
An unmarried woman or a virgin is anxious about the things of the Lord,  
so that she may be holy in both body and spirit.  
A married woman, on the other hand,  
is anxious about the things of the world,  
how she may please her husband.  
I am telling you this for your own benefit,  
not to impose a restraint upon you,  
but for the sake of propriety  
and adherence to the Lord without distraction.  

***

::: {.red}
#### Gospel Acclamation [Matthew 4:16]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
The people who sit in darkness have seen a great light;  
on those dwelling in a land overshadowed by death,  
light has arisen. **[℟.]{.red}**  

***

::: {.red}
#### Gospel [Mark 1:21-28]{style="float:right" .small}
:::

Then they came to Capernaum,  
and on the sabbath Jesus entered the synagogue and taught.  
The people were astonished at his teaching,  
for he taught them as one having authority and not as the scribes.  
In their synagogue was a man with an unclean spirit;  
he cried out, "What have you to do with us, Jesus of Nazareth?  
Have you come to destroy us?  
I know who you are—the Holy One of God!"  
Jesus rebuked him and said,  
"Quiet! Come out of him!"  
The unclean spirit convulsed him and with a loud cry came out of him.  
All were amazed and asked one another,  
"What is this?  
A new teaching with authority.  
He commands even the unclean spirits and they obey him."  
His fame spread everywhere throughout the whole region of Galilee.  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

::: {.red}
### &nbsp; Year C

#### First Reading [Jeremiah 1:4-5, 17-19]{style="float:right" .small}
:::

The word of the LORD came to me, saying:  
&emsp; Before I formed you in the womb I knew you,  
&emsp; &emsp; before you were born I dedicated you,  
&emsp; &emsp; a prophet to the nations I appointed you.  

&emsp; But do you gird your loins;  
&emsp; &emsp; stand up and tell them  
&emsp; &emsp; all that I command you.  
&emsp; Be not crushed on their account,  
&emsp; &emsp; as though I would leave you crushed before them;  
&emsp; for it is I this day  
&emsp; &emsp; who have made you a fortified city,  
&emsp; a pillar of iron, a wall of brass,  
&emsp; &emsp; against the whole land:  
&emsp; against Judah’s kings and princes,  
&emsp; &emsp; against its priests and people.  
&emsp; They will fight against you but not prevail over you,  
&emsp; &emsp; for I am with you to deliver you, says the LORD.  

***

::: {.red}
#### Responsorial Psalm [Psalm 71:1-2, 3-4, 5-6, 15-17]{style="float:right" .small}
:::

**[℟.]{.red}** **I will sing of your salvation.**  

In you, O LORD, I take refuge;  
&emsp; let me never be put to shame.  
In your justice rescue me, and deliver me;  
&emsp; incline your ear to me, and save me. **[℟.]{.red}**  

Be my rock of refuge,  
&emsp; a stronghold to give me safety,  
&emsp; for you are my rock and my fortress.  
O my God, rescue me from the hand of the wicked. **[℟.]{.red}** 

For you are my hope, O Lord;  
&emsp; my trust, O God, from my youth.  
On you I depend from birth;  
&emsp; from my mother’s womb you are my strength. **[℟.]{.red}** 

My mouth shall declare your justice,  
&emsp; day by day your salvation.  
O God, you have taught me from my youth,  
&emsp; and till the present I proclaim your wondrous deeds. **[℟.]{.red}**

***

::: {.red}
#### Second Reading [1 Corinthians 12:31—13:13 or 13:4-13]{style="float:right" .small}
:::

Brothers and sisters:  
Strive eagerly for the greatest spiritual gifts.  
But I shall show you a still more excellent way.  

If I speak in human and angelic tongues,  
but do not have love,  
I am a resounding gong or a clashing cymbal.  
And if I have the gift of prophecy,  
and comprehend all mysteries and all knowledge;  
if I have all faith so as to move mountains,  
but do not have love, I am nothing.  
If I give away everything I own,  
and if I hand my body over so that I may boast,  
but do not have love, I gain nothing.  

Love is patient, love is kind.  
It is not jealous, it is not pompous,  
It is not inflated, it is not rude,  
it does not seek its own interests,  
it is not quick-tempered, it does not brood over injury,  
it does not rejoice over wrongdoing  
but rejoices with the truth.  
It bears all things, believes all things,  
hopes all things, endures all things.  

Love never fails.  
If there are prophecies, they will be brought to nothing;  
if tongues, they will cease;  
if knowledge, it will be brought to nothing.  
For we know partially and we prophesy partially,  
but when the perfect comes, the partial will pass away.  
When I was a child, I used to talk as a child,  
think as a child, reason as a child;  
when I became a man, I put aside childish things.  
At present we see indistinctly, as in a mirror,  
but then face to face.  
At present I know partially;  
then I shall know fully, as I am fully known.  
So faith, hope, love remain, these three;  
but the greatest of these is love.  

[Or:]{.red}  

Brothers and sisters:  
Love is patient, love is kind.  
It is not jealous, it is not pompous,  
it is not inflated, it is not rude,  
it does not seek its own interests,  
it is not quick-tempered, it does not brood over injury,  
it does not rejoice over wrongdoing but rejoices with the truth.  
It bears all things, believes all things,  
hopes all things, endures all things.  

Love never fails.  
If there are prophecies, they will be brought to nothing;  
if tongues, they will cease;  
if knowledge, it will be brought to nothing.  
For we know partially and we prophesy partially,  
but when the perfect comes, the partial will pass away.  
When I was a child, I used to talk as a child,  
think as a child, reason as a child;  
when I became a man, I put aside childish things.  
At present we see indistinctly, as in a mirror,  
but then face to face.  
At present I know partially;  
then I shall know fully, as I am fully known.  
So faith, hope, love remain, these three;  
but the greatest of these is love.  

***

::: {.red}
#### Gospel Acclamation [Luke 4:18]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
The Lord sent me to bring glad tidings to the poor,  
to proclaim liberty to captives. **[℟.]{.red}** 

***

::: {.red}
#### Gospel [Luke 4:21-30]{style="float:right" .small}
:::

Jesus began speaking in the synagogue, saying:  
“Today this Scripture passage is fulfilled in your hearing.”  
And all spoke highly of him  
and were amazed at the gracious words that came from his mouth.  
They also asked, “Isn’t this the son of Joseph?”  
He said to them, “Surely you will quote me this proverb,  
‘Physician, cure yourself,’ and say,  
‘Do here in your native place  
the things that we heard were done in Capernaum.’”  
And he said, “Amen, I say to you,  
no prophet is accepted in his own native place.  
Indeed, I tell you,  
there were many widows in Israel in the days of Elijah  
when the sky was closed for three and a half years  
and a severe famine spread over the entire land.  
It was to none of these that Elijah was sent,  
but only to a widow in Zarephath in the land of Sidon.  
Again, there were many lepers in Israel  
during the time of Elisha the prophet;  
yet not one of them was cleansed, but only Naaman the Syrian.”  
When the people in the synagogue heard this,  
they were all filled with fury.  
They rose up, drove him out of the town,  
and led him to the brow of the hill  
on which their town had been built,  
to hurl him down headlong.  
But Jesus passed through the midst of them and went away.

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

</details>
::::

::: {.red}
## Music Selections
:::

::: {.titlered}
### &nbsp; Year A
:::
{{< var text.yeara >}}

```{python}
#| label: Year A
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['a'], urls=videos)
```

::: {.titlered}
### &nbsp; Year B
:::
{{< var text.yearb >}}

```{python}
#| label: Year B
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['b'], urls=videos)
```

::: {.titlered}
### &nbsp; Year C
:::
{{< var text.yearc >}}

```{python}
#| label: Year C
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['c'], urls=videos)
```


```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'], urls=videos)
```
