---
title: "SEVENTH SUNDAY OF ORDINARY TIME"
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  a:
    processional:
      list:
        - name: "Immortal, Invisible, God Only Wise"
          book: BB
          priority: required
    psalm:
      list:
        - name: "The Lord is kind and merciful."
          book: RA
          priority: required
    offertory:
      list:
        - name: "Holy Wisdom, Lamp of Learning"
          book: BB
          priority: required
    communion:
      list:
        - name: ""
          book: BB
          priority: required
    meditation:
      list:
        - name: "Jesu, Joy of Our Desiring"
          book: BB
          priority: required
    recessional:
      list:
        - name: "Praise, My Soul, the King of Heaven"
          book: BB
          priority: required
  b:
    processional:
      list:
        - name: "Gather Us In"
          book: BB
          priority: preferred
    psalm:
      list:
        - name: "Lord, heal my soul, for I have sinned against
you."
          book: RA
          priority: required
    offertory:
      list:
        - name: ""
          book: BB
          priority: required
    communion:
      list:
        - name: "We Remember"
          book: BB
          priority: required
    meditation:
      list:
        - name: ""
          book: BB
          priority: required
    recessional:
      list:
        - name: "O God, Beyond All Praising"
          book: BB
          priority: preferred
  c:
    processional:
      list:
        - name: ""
          book: BB
          priority: required
    psalm:
      list:
        - name: "The Lord is kind and merciful."
          book: RA
          priority: required
    offertory:
      list:
        - name: "There’s a Wideness in God’s Mercy"
          book: BB
          priority: required
    communion:
      list:
        - name: ""
          book: BB
          priority: required
    meditation:
      list:
        - name: "Love One Another"
          book: BB
          priority: required
    recessional:
      list:
        - name: "Praise, My Soul, the King of Heaven"
          book: BB
          priority: required
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
import yaml
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)

# Video links
with open('../../_hymns.yml', 'r') as vf:
    videos = yaml.safe_load(vf)
```

:::  {.red}
#### **Themes**
:::

[Year A:]{.red} forgiveness, love, mercy  
[Year B:]{.red} forgiveness, authority, pardon, mercy  
[Year C:]{.red} mercy, pardon, faith  

:::  {.red}
#### **Entrance Antiphon**
:::

> O Lord, I trust in your merciful love.  
> My heart will rejoice in your salvation.  
> I will sing to the Lord who has been bountiful with me.

:::  {.red}
#### **Communion Antiphon**
:::

> I will recount all your wonders,  
> I will rejoice in you and be glad,  
> and sing psalms to your name, O Most High.  
> 
> [Or:]{.red}  
> 
> Lord, I have come to believe that you are the Christ,  
> the Son of the living God, who is coming into this world.

:::: {.content-visible when-format="html"}
::: {.red}
### Readings
:::

<details>
  <summary>Click to view the readings for this liturgy.</summary>

::: {.red}
### &nbsp; Year A

#### First Reading [Leviticus 19:1-2, 17-18]{style="float:right" .small}
:::

The LORD said to Moses,  
"Speak to the whole Israelite community and tell them:  
Be holy, for I, the LORD, your God, am holy.  

"You shall not bear hatred for your brother or sister in your heart.  
Though you may have to reprove your fellow citizen,  
do not incur sin because of him.  
Take no revenge and cherish no grudge against any of your people.  
You shall love your neighbor as yourself.  
I am the LORD."  

***

::: {.red}
#### Responsorial Psalm [Psalm 103:1-2, 3-4, 8, 10, 12-13]{style="float:right" .small}
:::

**[℟.]{.red}** **The Lord is kind and merciful.**  

Bless the LORD, O my soul;  
and all my being, bless his holy name.  
Bless the LORD, O my soul,  
and forget not all his benefits. **[℟.]{.red}**  

He pardons all your iniquities,  
heals all your ills.  
He redeems your life from destruction,  
crowns you with kindness and compassion. **[℟.]{.red}**  

Merciful and gracious is the LORD,  
slow to anger and abounding in kindness.  
Not according to our sins does he deal with us,  
nor does he requite us according to our crimes. **[℟.]{.red}**  

As far as the east is from the west,  
so far has he put our transgressions from us.  
As a father has compassion on his children,  
so the LORD has compassion on those who fear him. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [1 Corinthians 3:16-23]{style="float:right" .small}
:::

Brothers and sisters:  
Do you not know that you are the temple of God,  
and that the Spirit of God dwells in you?  
If anyone destroys God's temple, God will destroy that person;  
for the temple of God, which you are, is holy.  

Let no one deceive himself.  
If any one among you considers himself wise in this age,  
let him become a fool, so as to become wise.  
For the wisdom of this world is foolishness in the eyes of God,  
for it is written:  
*God catches the wise in their own ruses,*  
and again:  
*The Lord knows the thoughts of the wise,*  
*that they are vain.*  

So let no one boast about human beings, for everything belongs to you,  
Paul or Apollos or Cephas,  
or the world or life or death,  
or the present or the future:  
all belong to you, and you to Christ, and Christ to God.  

***

::: {.red}
#### Gospel Acclamation [1 John 2:5]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
Whoever keeps the word of Christ,  
the love of God is truly perfected in him. **[℟.]{.red}**

***

::: {.red}
#### Gospel [Matthew 5:38-48]{style="float:right" .small}
:::

Jesus said to his disciples:  
"You have heard that it was said,  
*An eye for an eye and a tooth for a tooth.*  
But I say to you, offer no resistance to one who is evil.  
When someone strikes you on your right cheek,  
turn the other one as well.  
If anyone wants to go to law with you over your tunic,  
hand over your cloak as well.  
Should anyone press you into service for one mile,  
go for two miles.  
Give to the one who asks of you,  
and do not turn your back on one who wants to borrow.  

"You have heard that it was said,  
*You shall love your neighbor and hate your enemy.*  
But I say to you, love your enemies  
and pray for those who persecute you,  
that you may be children of your heavenly Father,  
for he makes his sun rise on the bad and the good,  
and causes rain to fall on the just and the unjust.  
For if you love those who love you, what recompense will you have?  
Do not the tax collectors do the same?  
And if you greet your brothers only,  
what is unusual about that?  
Do not the pagans do the same?  
So be perfect, just as your heavenly Father is perfect."  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

::: {.red}
### &nbsp; Year B

#### First Reading [Isaiah 43:18-19, 21-22, 24b-25]{style="float:right" .small}
:::

Thus says the LORD:  
Remember not the events of the past,  
the things of long ago consider not;  
see, I am doing something new!  
Now it springs forth, do you not perceive it?  
In the desert I make a way,  
in the wasteland, rivers.  
The people I formed for myself,  
that they might announce my praise.  
Yet you did not call upon me, O Jacob,  
for you grew weary of me, O Israel.  
You burdened me with your sins,  
and wearied me with your crimes.  
It is I, I, who wipe out,  
for my own sake, your offenses;  
your sins I remember no more.  

***

::: {.red}
#### Responsorial Psalm [Psalm 41:2-3, 4-5, 13-14]{style="float:right" .small}
:::

**[℟.]{.red}** **Lord, heal my soul, for I have sinned against you.**  

Blessed is the one who has regard for the lowly and the poor;  
in the day of misfortune the LORD will deliver him.  
The LORD will keep and preserve him;  
and make him blessed on earth,  
and not give him over to the will of his enemies. **[℟.]{.red}**  

The LORD will help him on his sickbed,  
he will take away all his ailment when he is ill.  
Once I said, "O LORD, have pity on me;  
heal me, though I have sinned against you." **[℟.]{.red}**  

But because of my integrity you sustain me  
and let me stand before you forever.  
Blessed be the LORD, the God of Israel,  
from all eternity. Amen. Amen. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [2 Corinthians 1:18-22]{style="float:right" .small}
:::

Brothers and sisters:  
As God is faithful,  
our word to you is not "yes" and "no."  
For the Son of God, Jesus Christ,  
who was proclaimed to you by us, Silvanus and Timothy and me,  
was not "yes" and "no, " but "yes" has been in him.  
For however many are the promises of God, their Yes is in him;  
therefore, the Amen from us also goes through him to God for glory.  
But the one who gives us security with you in Christ  
and who anointed us is God;  
he has also put his seal upon us  
and given the Spirit in our hearts as a first installment.  

***

::: {.red}
#### Gospel Acclamation [Luke 4.18-19]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
The Lord sent me to bring glad tidings to the poor,  
and to proclaim liberty to captives. **[℟.]{.red}**  

***

::: {.red}
#### Gospel [Mark 2:1-12]{style="float:right" .small}
:::

When Jesus returned to Capernaum after some days,  
it became known that he was at home.  
Many gathered together so that there was no longer room for them,  
not even around the door,  
and he preached the word to them.  
They came bringing to him a paralytic carried by four men.  
Unable to get near Jesus because of the crowd,  
they opened up the roof above him.  
After they had broken through,  
they let down the mat on which the paralytic was lying.  
When Jesus saw their faith, he said to the paralytic,  
"Child, your sins are forgiven."  
Now some of the scribes were sitting there asking themselves,  
"Why does this man speak that way? He is blaspheming.  
Who but God alone can forgive sins?"  
Jesus immediately knew in his mind  
what they were thinking to themselves,  
so he said, "Why are you thinking such things in your hearts?  
Which is easier, to say to the paralytic,  
'Your sins are forgiven,'  
or to say, 'Rise, pick up your mat and walk?'  
But that you may know  
that the Son of Man has authority to forgive sins on earth"  
-he said to the paralytic,  
"I say to you, rise, pick up your mat, and go home."  
He rose, picked up his mat at once,  
and went away in the sight of everyone.  
They were all astounded  
and glorified God, saying, "We have never seen anything like this."  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

::: {.red}
### &nbsp; Year C

#### First Reading [1 Samuel 26:2, 7-9, 12-13, 22-23]{style="float:right" .small}
:::

In those days, Saul went down to the desert of Ziph  
with three thousand picked men of Israel,  
to search for David in the desert of Ziph.  
So David and Abishai went among Saul’s soldiers by night  
and found Saul lying asleep within the barricade,  
with his spear thrust into the ground at his head  
and Abner and his men sleeping around him.  

Abishai whispered to David:  
“God has delivered your enemy into your grasp this day.  
Let me nail him to the ground with one thrust of the spear;  
I will not need a second thrust!”  
But David said to Abishai, “Do not harm him,  
for who can lay hands on the LORD’s anointed and remain unpunished?”  
So David took the spear and the water jug from their place at Saul’s head,  
and they got away without anyone’s seeing or knowing or awakening.  
All remained asleep,  
because the LORD had put them into a deep slumber.  

Going across to an opposite slope,  
David stood on a remote hilltop  
at a great distance from Abner, son of Ner, and the troops.  
He said: “Here is the king’s spear.  
Let an attendant come over to get it.  
The LORD will reward each man for his justice and faithfulness.  
Today, though the LORD delivered you into my grasp,  
I would not harm the LORD’s anointed.”

***

::: {.red}
#### Responsorial Psalm [Psalm 103:1-2, 3-4, 8, 10, 12-13]{style="float:right" .small}
:::

**[℟.]{.red}** **The Lord is kind and merciful.**  

Bless the LORD, O my soul;  
&emsp; and all my being, bless his holy name.  
Bless the LORD, O my soul,  
&emsp; and forget not all his benefits. **[℟.]{.red}**  

He pardons all your iniquities,  
&emsp; heals all your ills.  
He redeems your life from destruction,  
&emsp; crowns you with kindness and compassion. **[℟.]{.red}** 

Merciful and gracious is the LORD,  
&emsp; slow to anger and abounding in kindness.  
Not according to our sins does he deal with us,  
&emsp; nor does he requite us according to our crimes. **[℟.]{.red}** 

As far as the east is from the west,  
&emsp; so far has he put our transgressions from us.  
As a father has compassion on his children,  
&emsp; so the LORD has compassion on those who fear him. **[℟.]{.red}** 

***

::: {.red}
#### Second Reading [1 Corinthians 15:45-49]{style="float:right" .small}
:::

Brothers and sisters:  
It is written, *The first man, Adam, became a living being,*  
the last Adam a life-giving spirit.  
But the spiritual was not first;  
rather the natural and then the spiritual.  
The first man was from the earth, earthly;  
the second man, from heaven.  
As was the earthly one, so also are the earthly,  
and as is the heavenly one, so also are the heavenly.  
Just as we have borne the image of the earthly one,  
we shall also bear the image of the heavenly one.  

***

::: {.red}
#### Gospel Acclamation [John 13:34]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
I give you a new commandment, says the Lord:  
love one another as I have loved you. **[℟.]{.red}** 

***

::: {.red}
#### Gospel [Luke 6:27-38]{style="float:right" .small}
:::

Jesus said to his disciples:  
“To you who hear I say,  
love your enemies, do good to those who hate you,  
bless those who curse you, pray for those who mistreat you.  
To the person who strikes you on one cheek,  
offer the other one as well,  
and from the person who takes your cloak,  
do not withhold even your tunic.  
Give to everyone who asks of you,  
and from the one who takes what is yours do not demand it back.  
Do to others as you would have them do to you.  
For if you love those who love you,  
what credit is that to you?  
Even sinners love those who love them.  
And if you do good to those who do good to you,  
what credit is that to you?  
Even sinners do the same.  
If you lend money to those from whom you expect repayment,  
what credit is that to you?  
Even sinners lend to sinners,  
and get back the same amount.  
But rather, love your enemies and do good to them,  
and lend expecting nothing back;  
then your reward will be great  
and you will be children of the Most High,  
for he himself is kind to the ungrateful and the wicked.  
Be merciful, just as your Father is merciful.  

“Stop judging and you will not be judged.  
Stop condemning and you will not be condemned.  
Forgive and you will be forgiven.  
Give, and gifts will be given to you;  
a good measure, packed together, shaken down, and overflowing,  
will be poured into your lap.  
For the measure with which you measure  
will in return be measured out to you.”

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

</details>
::::

::: {.red}
## Music Selections
:::

::: {.titlered}
### &nbsp; Year A
:::
{{< var text.yeara >}}

```{python}
#| label: Year A
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['a'], urls=videos)
```

::: {.titlered}
### &nbsp; Year B
:::
{{< var text.yearb >}}

```{python}
#| label: Year B
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['b'], urls=videos)
```

::: {.titlered}
### &nbsp; Year C
:::
{{< var text.yearc >}}

```{python}
#| label: Year C
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['c'], urls=videos)
```


```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'], urls=videos)
```
