---
title: "TENTH SUNDAY IN ORDINARY TIME"
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  a:
    processional:
      list:
        - name: ""
          book: BB
          priority: required
    psalm:
      list:
        - name: "To the upright I will show the saving power of God."
          book: RA
          priority: required
    offertory:
      list:
        - name: "The Summons"
          book: BB
          priority: required
    communion:
      list:
        - name: ""
          book: BB
          priority: required
    meditation:
      list:
        - name: ""
          book: BB
          priority: required
    recessional:
      list:
        - name: "God Is Love"
          book: BB
          priority: required
  b:
    processional:
      list:
        - name: ""
          book: BB
          priority: required
    psalm:
      list:
        - name: "With the Lord there is mercy, and fullness of redemption."
          book: RA
          priority: required
    offertory:
      list:
        - name: "The Lord Is My Light"
          composer: Walker
          book: BB
          priority: required
    communion:
      list:
        - name: ""
          book: BB
          priority: required
    meditation:
      list:
        - name: ""
          book: BB
          priority: required
    recessional:
      list:
        - name: "God is Love"
          book: BB
          priority: preferred
  c:
    processional:
      list:
        - name: ""
          book: BB
          priority: required
    psalm:
      list:
        - name: "I will praise you, Lord, for you have rescued me."
          book: RA
          priority: required
    offertory:
      list:
        - name: "The Lord Is My Light"
          composer: Walker
          book: BB
          priority: required
    communion:
      list:
        - name: ""
          book: BB
          priority: required
    meditation:
      list:
        - name: ""
          book: BB
          priority: required
    recessional:
      list:
        - name: "God Is Love"
          book: BB
          priority: required
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
import yaml
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)

# Video links
with open('../../_hymns.yml', 'r') as vf:
    videos = yaml.safe_load(vf)
```

:::  {.red}
#### **Themes**
:::

[Year A:]{.red} faith, discipleship, providence  
[Year B:]{.red} salvation, deliverance, faith, mercy  
[Year C:]{.red} power of God, healing, light  

:::  {.red}
#### **Entrance Antiphon**
:::

> The Lord is my light and my salvation; whom shall I fear?  
> The Lord is the stronghold of my life; whom should I dread?  
> When those who do evil draw near, they stumble and fall.  

:::  {.red}
#### **Communion Antiphon**
:::

> The Lord is my rock, my fortress, and my deliverer;  
> my God is my saving strength.  
>  
> [Or:]{.red}
> God is love, and whoever abides in love  
> abides in God, and God in him.  

:::: {.content-visible when-format="html"}
::: {.red}
### Readings
:::

<details>
  <summary>Click to view the readings for this liturgy.</summary>

::: {.red}
### &nbsp; Year A

#### First Reading [PASSAGE]{style="float:right" .small}
:::

Text  
&emsp; indented as needed

***

::: {.red}
#### Responsorial Psalm [PASSAGE]{style="float:right" .small}
:::

**[℟.]{.red}** **REFRAIN**  

Verse one,  
&emsp; indented as needed. **[℟.]{.red}**  

Verse two,  
&emsp; and so on as needed. **[℟.]{.red}**  

Verse three,  
&emsp; and so on as needed. **[℟.]{.red}**  

Verse four,  
&emsp; and so on as needed. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [PASSAGE]{style="float:right" .small}
:::

Text

***

::: {.red}
#### Gospel Acclamation [PASSAGE]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
Verse **[℟.]{.red}**

***

::: {.red}
#### Gospel [PASSAGE]{style="float:right" .small}
:::

Text

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

::: {.red}
### &nbsp; Year B

#### First Reading [Genesis 3:9-15]{style="float:right" .small}
:::

After the man, Adam, had eaten of the tree,  
the LORD God called to the man and asked him, "Where are you?"  
He answered, "I heard you in the garden;  
but I was afraid, because I was naked,  
so I hid myself."  
Then he asked, "Who told you that you were naked?  
You have eaten, then,  
from the tree of which I had forbidden you to eat!"  
The man replied, "The woman whom you put here with me—  
she gave me fruit from the tree, and so I ate it."  
The LORD God then asked the woman,  
"Why did you do such a thing?"  
The woman answered, "The serpent tricked me into it, so I ate it."  

Then the LORD God said to the serpent:  
"Because you have done this, you shall be banned  
from all the animals  
and from all the wild creatures;  
on your belly shall you crawl,  
and dirt shall you eat  
all the days of your life.  
I will put enmity between you and the woman,  
and between your offspring and hers;  
he will strike at your head,  
while you strike at his heel."  

***

::: {.red}
#### Responsorial Psalm [Psalm 130:1-2, 3-4, 5-6, 7-8]{style="float:right" .small}
:::

**[℟.]{.red}** **With the Lord there is mercy, and fullness of redemption.**  

Out of the depths I cry to you, O LORD;  
LORD, hear my voice!  
Let your ears be attentive  
to my voice in supplication. **[℟.]{.red}**  

If you, O LORD, mark iniquities,  
LORD, who can stand?  
But with you is forgiveness,  
that you may be revered. **[℟.]{.red}**  

I trust in the LORD;  
my soul trusts in his word.  
More than sentinels wait for the dawn,  
let Israel wait for the LORD. **[℟.]{.red}**  

For with the LORD is kindness  
and with him is plenteous redemption  
and he will redeem Israel  
from all their iniquities. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [2 Corinthians 4:13—5:1]{style="float:right" .small}
:::

Brothers and sisters:  
Since we have the same spirit of faith,  
according to what is written, *I believed, therefore I spoke*,  
we too believe and therefore we speak,  
knowing that the one who raised the Lord Jesus  
will raise us also with Jesus  
and place us with you in his presence.  
Everything indeed is for you,  
so that the grace bestowed in abundance on more and more people  
may cause the thanksgiving to overflow for the glory of God.  
Therefore, we are not discouraged;  
rather, although our outer self is wasting away,  
our inner self is being renewed day by day.  
For this momentary light affliction  
is producing for us an eternal weight of glory  
beyond all comparison,  
as we look not to what is seen but to what is unseen;  
for what is seen is transitory, but what is unseen is eternal.  
For we know that if our earthly dwelling, a tent,  
should be destroyed,  
we have a building from God,  
a dwelling not made with hands, eternal in heaven.  

***

::: {.red}
#### Gospel Acclamation [John 12:31b-32]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
Now the ruler of the world will be driven out, says the Lord;  
and when I am lifted up from the earth, I will draw everyone to myself. **[℟.]{.red}**  

***

::: {.red}
#### Gospel [Mark 3:20-35]{style="float:right" .small}
:::

Jesus came home with his disciples.  
Again the crowd gathered,  
making it impossible for them even to eat.  
When his relatives heard of this they set out to seize him,  
for they said, "He is out of his mind."  
The scribes who had come from Jerusalem said,  
"He is possessed by Beelzebul,"  
and "By the prince of demons he drives out demons."  

Summoning them, he began to speak to them in parables,  
"How can Satan drive out Satan?  
If a kingdom is divided against itself,  
that kingdom cannot stand.  
And if a house is divided against itself,  
that house will not be able to stand.  
And if Satan has risen up against himself  
and is divided, he cannot stand;  
that is the end of him.  
But no one can enter a strong man's house to plunder his property  
unless he first ties up the strong man.  
Then he can plunder the house.  
Amen, I say to you,  
all sins and all blasphemies that people utter will be  
forgiven them.  
But whoever blasphemes against the Holy Spirit  
will never have forgiveness,  
but is guilty of an everlasting sin."  
For they had said, "He has an unclean spirit."  

His mother and his brothers arrived.  
Standing outside they sent word to him and called him.  
A crowd seated around him told him,  
"Your mother and your brothers and your sisters  
are outside asking for you."  
But he said to them in reply,  
"Who are my mother and my brothers?"  
And looking around at those seated in the circle he said,  
"Here are my mother and my brothers.  
For whoever does the will of God  
is my brother and sister and mother."  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

::: {.red}
### &nbsp; Year C

#### First Reading [PASSAGE]{style="float:right" .small}
:::

Text  
&emsp; indented as needed.

***

::: {.red}
#### Responsorial Psalm [PASSAGE]{style="float:right" .small}
:::

**[℟.]{.red}** **REFRAIN**  

Verse one,  
&emsp; indented as needed. **[℟.]{.red}**  

Verse two,  
&emsp; and so on as needed. **[℟.]{.red}**  

Verse three,  
&emsp; indented as needed. **[℟.]{.red}**  

Verse four,  
&emsp; and so on as needed. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [PASSAGE]{style="float:right" .small}
:::

Text

***

::: {.red}
#### Gospel Acclamation [PASSAGE]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
Verse **[℟.]{.red}** 

***

::: {.red}
#### Gospel [PASSAGE]{style="float:right" .small}
:::

Text

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

</details>
::::

::: {.red}
## Music Selections
:::

::: {.titlered}
### &nbsp; Year A
:::
{{< var text.yeara >}}

```{python}
#| label: Year A
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['a'], urls=videos)
```

::: {.titlered}
### &nbsp; Year B
:::
{{< var text.yearb >}}

```{python}
#| label: Year B
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['b'], urls=videos)
```

::: {.titlered}
### &nbsp; Year C
:::
{{< var text.yearc >}}

```{python}
#| label: Year C
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['c'], urls=videos)
```


```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'], urls=videos)
```
